"""Contains all the data models used in inputs/outputs"""

from .add_voice_to_provider_dto import AddVoiceToProviderDTO
from .ai_edge_condition import AIEdgeCondition
from .ai_edge_condition_type import AIEdgeConditionType
from .analysis import Analysis
from .analysis_cost import AnalysisCost
from .analysis_cost_analysis_type import AnalysisCostAnalysisType
from .analysis_cost_breakdown import AnalysisCostBreakdown
from .analysis_cost_model import AnalysisCostModel
from .analysis_cost_type import AnalysisCostType
from .analysis_plan import AnalysisPlan
from .analysis_structured_data import AnalysisStructuredData
from .analytics_operation import AnalyticsOperation
from .analytics_operation_column import AnalyticsOperationColumn
from .analytics_operation_operation import AnalyticsOperationOperation
from .analytics_query import AnalyticsQuery
from .analytics_query_dto import AnalyticsQueryDTO
from .analytics_query_group_by import AnalyticsQueryGroupBy
from .analytics_query_result import AnalyticsQueryResult
from .analytics_query_result_result_item import AnalyticsQueryResultResultItem
from .analytics_query_table import AnalyticsQueryTable
from .anthropic_credential import AnthropicCredential
from .anthropic_credential_provider import AnthropicCredentialProvider
from .anthropic_model import AnthropicModel
from .anthropic_model_model import AnthropicModelModel
from .anthropic_model_provider import AnthropicModelProvider
from .anthropic_thinking_config import AnthropicThinkingConfig
from .anthropic_thinking_config_type import AnthropicThinkingConfigType
from .anyscale_credential import AnyscaleCredential
from .anyscale_credential_provider import AnyscaleCredentialProvider
from .anyscale_model import AnyscaleModel
from .anyscale_model_provider import AnyscaleModelProvider
from .api_request import ApiRequest
from .api_request_metadata import ApiRequestMetadata
from .api_request_method import ApiRequestMethod
from .api_request_mode import ApiRequestMode
from .api_request_type import ApiRequestType
from .artifact import Artifact
from .artifact_plan import ArtifactPlan
from .assembly_ai_credential import AssemblyAICredential
from .assembly_ai_credential_provider import AssemblyAICredentialProvider
from .assembly_ai_transcriber import AssemblyAITranscriber
from .assembly_ai_transcriber_language import AssemblyAITranscriberLanguage
from .assembly_ai_transcriber_provider import AssemblyAITranscriberProvider
from .assistant import Assistant
from .assistant_background_sound import AssistantBackgroundSound
from .assistant_client_messages import AssistantClientMessages
from .assistant_custom_endpointing_rule import AssistantCustomEndpointingRule
from .assistant_custom_endpointing_rule_type import AssistantCustomEndpointingRuleType
from .assistant_first_message_mode import AssistantFirstMessageMode
from .assistant_hook_action_base import AssistantHookActionBase
from .assistant_hook_filter import AssistantHookFilter
from .assistant_hook_filter_type import AssistantHookFilterType
from .assistant_hooks import AssistantHooks
from .assistant_hooks_on import AssistantHooksOn
from .assistant_metadata import AssistantMetadata
from .assistant_overrides import AssistantOverrides
from .assistant_overrides_background_sound import AssistantOverridesBackgroundSound
from .assistant_overrides_client_messages import AssistantOverridesClientMessages
from .assistant_overrides_first_message_mode import AssistantOverridesFirstMessageMode
from .assistant_overrides_metadata import AssistantOverridesMetadata
from .assistant_overrides_server_messages import AssistantOverridesServerMessages
from .assistant_overrides_variable_values import AssistantOverridesVariableValues
from .assistant_paginated_response import AssistantPaginatedResponse
from .assistant_server_messages import AssistantServerMessages
from .auto_reload_plan import AutoReloadPlan
from .azure_blob_storage_bucket_plan import AzureBlobStorageBucketPlan
from .azure_credential import AzureCredential
from .azure_credential_provider import AzureCredentialProvider
from .azure_credential_region import AzureCredentialRegion
from .azure_credential_service import AzureCredentialService
from .azure_open_ai_credential import AzureOpenAICredential
from .azure_open_ai_credential_models import AzureOpenAICredentialModels
from .azure_open_ai_credential_provider import AzureOpenAICredentialProvider
from .azure_open_ai_credential_region import AzureOpenAICredentialRegion
from .azure_speech_transcriber import AzureSpeechTranscriber
from .azure_speech_transcriber_language import AzureSpeechTranscriberLanguage
from .azure_speech_transcriber_provider import AzureSpeechTranscriberProvider
from .azure_voice import AzureVoice
from .azure_voice_preset_voice_options import AzureVoicePresetVoiceOptions
from .azure_voice_provider import AzureVoiceProvider
from .backoff_plan import BackoffPlan
from .backoff_plan_type import BackoffPlanType
from .bash_tool import BashTool
from .bash_tool_name import BashToolName
from .bash_tool_sub_type import BashToolSubType
from .bash_tool_type import BashToolType
from .bash_tool_with_tool_call import BashToolWithToolCall
from .bash_tool_with_tool_call_name import BashToolWithToolCallName
from .bash_tool_with_tool_call_sub_type import BashToolWithToolCallSubType
from .bash_tool_with_tool_call_type import BashToolWithToolCallType
from .bot_message import BotMessage
from .both_custom_endpointing_rule import BothCustomEndpointingRule
from .both_custom_endpointing_rule_type import BothCustomEndpointingRuleType
from .bucket_plan import BucketPlan
from .byo_phone_number import ByoPhoneNumber
from .byo_phone_number_provider import ByoPhoneNumberProvider
from .byo_phone_number_status import ByoPhoneNumberStatus
from .byo_sip_trunk_credential import ByoSipTrunkCredential
from .byo_sip_trunk_credential_provider import ByoSipTrunkCredentialProvider
from .call import Call
from .call_ended_reason import CallEndedReason
from .call_log_privileged import CallLogPrivileged
from .call_log_privileged_level import CallLogPrivilegedLevel
from .call_logs_paginated_response import CallLogsPaginatedResponse
from .call_paginated_response import CallPaginatedResponse
from .call_phone_call_provider import CallPhoneCallProvider
from .call_phone_call_transport import CallPhoneCallTransport
from .call_status import CallStatus
from .call_type import CallType
from .cartesia_credential import CartesiaCredential
from .cartesia_credential_provider import CartesiaCredentialProvider
from .cartesia_experimental_controls import CartesiaExperimentalControls
from .cartesia_experimental_controls_emotion import CartesiaExperimentalControlsEmotion
from .cartesia_experimental_controls_speed import CartesiaExperimentalControlsSpeed
from .cartesia_voice import CartesiaVoice
from .cartesia_voice_language import CartesiaVoiceLanguage
from .cartesia_voice_model import CartesiaVoiceModel
from .cartesia_voice_provider import CartesiaVoiceProvider
from .cerebras_credential import CerebrasCredential
from .cerebras_credential_provider import CerebrasCredentialProvider
from .cerebras_model import CerebrasModel
from .cerebras_model_model import CerebrasModelModel
from .cerebras_model_provider import CerebrasModelProvider
from .chat_completion_message import ChatCompletionMessage
from .chat_completion_message_metadata import ChatCompletionMessageMetadata
from .chat_completion_message_metadata_task_state import ChatCompletionMessageMetadataTaskState
from .chat_completion_message_role import ChatCompletionMessageRole
from .chat_completions_dto import ChatCompletionsDTO
from .chat_service_response import ChatServiceResponse
from .chunk_plan import ChunkPlan
from .chunk_plan_punctuation_boundaries import ChunkPlanPunctuationBoundaries
from .client_inbound_message import ClientInboundMessage
from .client_inbound_message_add_message import ClientInboundMessageAddMessage
from .client_inbound_message_add_message_type import ClientInboundMessageAddMessageType
from .client_inbound_message_control import ClientInboundMessageControl
from .client_inbound_message_control_control import ClientInboundMessageControlControl
from .client_inbound_message_control_type import ClientInboundMessageControlType
from .client_inbound_message_end_call import ClientInboundMessageEndCall
from .client_inbound_message_end_call_type import ClientInboundMessageEndCallType
from .client_inbound_message_say import ClientInboundMessageSay
from .client_inbound_message_say_type import ClientInboundMessageSayType
from .client_inbound_message_transfer import ClientInboundMessageTransfer
from .client_inbound_message_transfer_type import ClientInboundMessageTransferType
from .client_message import ClientMessage
from .client_message_conversation_update import ClientMessageConversationUpdate
from .client_message_conversation_update_type import ClientMessageConversationUpdateType
from .client_message_hang import ClientMessageHang
from .client_message_hang_type import ClientMessageHangType
from .client_message_language_change_detected import ClientMessageLanguageChangeDetected
from .client_message_language_change_detected_type import ClientMessageLanguageChangeDetectedType
from .client_message_metadata import ClientMessageMetadata
from .client_message_metadata_type import ClientMessageMetadataType
from .client_message_model_output import ClientMessageModelOutput
from .client_message_model_output_output import ClientMessageModelOutputOutput
from .client_message_model_output_type import ClientMessageModelOutputType
from .client_message_speech_update import ClientMessageSpeechUpdate
from .client_message_speech_update_role import ClientMessageSpeechUpdateRole
from .client_message_speech_update_status import ClientMessageSpeechUpdateStatus
from .client_message_speech_update_type import ClientMessageSpeechUpdateType
from .client_message_tool_calls import ClientMessageToolCalls
from .client_message_tool_calls_result import ClientMessageToolCallsResult
from .client_message_tool_calls_result_tool_call_result import ClientMessageToolCallsResultToolCallResult
from .client_message_tool_calls_result_type import ClientMessageToolCallsResultType
from .client_message_tool_calls_type import ClientMessageToolCallsType
from .client_message_transcript import ClientMessageTranscript
from .client_message_transcript_role import ClientMessageTranscriptRole
from .client_message_transcript_transcript_type import ClientMessageTranscriptTranscriptType
from .client_message_transcript_type import ClientMessageTranscriptType
from .client_message_transfer_update import ClientMessageTransferUpdate
from .client_message_transfer_update_from_step_record import ClientMessageTransferUpdateFromStepRecord
from .client_message_transfer_update_to_step_record import ClientMessageTransferUpdateToStepRecord
from .client_message_transfer_update_type import ClientMessageTransferUpdateType
from .client_message_user_interrupted import ClientMessageUserInterrupted
from .client_message_user_interrupted_type import ClientMessageUserInterruptedType
from .client_message_voice_input import ClientMessageVoiceInput
from .client_message_voice_input_type import ClientMessageVoiceInputType
from .client_message_workflow_node_started import ClientMessageWorkflowNodeStarted
from .client_message_workflow_node_started_node import ClientMessageWorkflowNodeStartedNode
from .client_message_workflow_node_started_type import ClientMessageWorkflowNodeStartedType
from .clone_voice_dto import CloneVoiceDTO
from .cloudflare_credential import CloudflareCredential
from .cloudflare_credential_provider import CloudflareCredentialProvider
from .cloudflare_r2_bucket_plan import CloudflareR2BucketPlan
from .compliance_plan import CompliancePlan
from .computer_tool import ComputerTool
from .computer_tool_name import ComputerToolName
from .computer_tool_sub_type import ComputerToolSubType
from .computer_tool_type import ComputerToolType
from .computer_tool_with_tool_call import ComputerToolWithToolCall
from .computer_tool_with_tool_call_name import ComputerToolWithToolCallName
from .computer_tool_with_tool_call_sub_type import ComputerToolWithToolCallSubType
from .computer_tool_with_tool_call_type import ComputerToolWithToolCallType
from .condition import Condition
from .condition_operator import ConditionOperator
from .condition_value import ConditionValue
from .cost_breakdown import CostBreakdown
from .create_anthropic_credential_dto import CreateAnthropicCredentialDTO
from .create_anthropic_credential_dto_provider import CreateAnthropicCredentialDTOProvider
from .create_anyscale_credential_dto import CreateAnyscaleCredentialDTO
from .create_anyscale_credential_dto_provider import CreateAnyscaleCredentialDTOProvider
from .create_assembly_ai_credential_dto import CreateAssemblyAICredentialDTO
from .create_assembly_ai_credential_dto_provider import CreateAssemblyAICredentialDTOProvider
from .create_assistant_dto import CreateAssistantDTO
from .create_assistant_dto_background_sound import CreateAssistantDTOBackgroundSound
from .create_assistant_dto_client_messages import CreateAssistantDTOClientMessages
from .create_assistant_dto_first_message_mode import CreateAssistantDTOFirstMessageMode
from .create_assistant_dto_metadata import CreateAssistantDTOMetadata
from .create_assistant_dto_server_messages import CreateAssistantDTOServerMessages
from .create_azure_credential_dto import CreateAzureCredentialDTO
from .create_azure_credential_dto_provider import CreateAzureCredentialDTOProvider
from .create_azure_credential_dto_region import CreateAzureCredentialDTORegion
from .create_azure_credential_dto_service import CreateAzureCredentialDTOService
from .create_azure_open_ai_credential_dto import CreateAzureOpenAICredentialDTO
from .create_azure_open_ai_credential_dto_models import CreateAzureOpenAICredentialDTOModels
from .create_azure_open_ai_credential_dto_provider import CreateAzureOpenAICredentialDTOProvider
from .create_azure_open_ai_credential_dto_region import CreateAzureOpenAICredentialDTORegion
from .create_bash_tool_dto import CreateBashToolDTO
from .create_bash_tool_dto_name import CreateBashToolDTOName
from .create_bash_tool_dto_sub_type import CreateBashToolDTOSubType
from .create_bash_tool_dto_type import CreateBashToolDTOType
from .create_byo_phone_number_dto import CreateByoPhoneNumberDTO
from .create_byo_phone_number_dto_provider import CreateByoPhoneNumberDTOProvider
from .create_byo_sip_trunk_credential_dto import CreateByoSipTrunkCredentialDTO
from .create_byo_sip_trunk_credential_dto_provider import CreateByoSipTrunkCredentialDTOProvider
from .create_call_dto import CreateCallDTO
from .create_cartesia_credential_dto import CreateCartesiaCredentialDTO
from .create_cartesia_credential_dto_provider import CreateCartesiaCredentialDTOProvider
from .create_cerebras_credential_dto import CreateCerebrasCredentialDTO
from .create_cerebras_credential_dto_provider import CreateCerebrasCredentialDTOProvider
from .create_cloudflare_credential_dto import CreateCloudflareCredentialDTO
from .create_cloudflare_credential_dto_provider import CreateCloudflareCredentialDTOProvider
from .create_computer_tool_dto import CreateComputerToolDTO
from .create_computer_tool_dto_name import CreateComputerToolDTOName
from .create_computer_tool_dto_sub_type import CreateComputerToolDTOSubType
from .create_computer_tool_dto_type import CreateComputerToolDTOType
from .create_custom_knowledge_base_dto import CreateCustomKnowledgeBaseDTO
from .create_custom_knowledge_base_dto_provider import CreateCustomKnowledgeBaseDTOProvider
from .create_custom_llm_credential_dto import CreateCustomLLMCredentialDTO
from .create_custom_llm_credential_dto_provider import CreateCustomLLMCredentialDTOProvider
from .create_customer_dto import CreateCustomerDTO
from .create_deep_infra_credential_dto import CreateDeepInfraCredentialDTO
from .create_deep_infra_credential_dto_provider import CreateDeepInfraCredentialDTOProvider
from .create_deep_seek_credential_dto import CreateDeepSeekCredentialDTO
from .create_deep_seek_credential_dto_provider import CreateDeepSeekCredentialDTOProvider
from .create_deepgram_credential_dto import CreateDeepgramCredentialDTO
from .create_deepgram_credential_dto_provider import CreateDeepgramCredentialDTOProvider
from .create_dtmf_tool_dto import CreateDtmfToolDTO
from .create_dtmf_tool_dto_type import CreateDtmfToolDTOType
from .create_eleven_labs_credential_dto import CreateElevenLabsCredentialDTO
from .create_eleven_labs_credential_dto_provider import CreateElevenLabsCredentialDTOProvider
from .create_end_call_tool_dto import CreateEndCallToolDTO
from .create_end_call_tool_dto_type import CreateEndCallToolDTOType
from .create_file_dto import CreateFileDTO
from .create_function_tool_dto import CreateFunctionToolDTO
from .create_function_tool_dto_type import CreateFunctionToolDTOType
from .create_gcp_credential_dto import CreateGcpCredentialDTO
from .create_gcp_credential_dto_provider import CreateGcpCredentialDTOProvider
from .create_ghl_tool_dto import CreateGhlToolDTO
from .create_ghl_tool_dto_type import CreateGhlToolDTOType
from .create_gladia_credential_dto import CreateGladiaCredentialDTO
from .create_gladia_credential_dto_provider import CreateGladiaCredentialDTOProvider
from .create_go_high_level_credential_dto import CreateGoHighLevelCredentialDTO
from .create_go_high_level_credential_dto_provider import CreateGoHighLevelCredentialDTOProvider
from .create_google_credential_dto import CreateGoogleCredentialDTO
from .create_google_credential_dto_provider import CreateGoogleCredentialDTOProvider
from .create_groq_credential_dto import CreateGroqCredentialDTO
from .create_groq_credential_dto_provider import CreateGroqCredentialDTOProvider
from .create_hume_credential_dto import CreateHumeCredentialDTO
from .create_hume_credential_dto_provider import CreateHumeCredentialDTOProvider
from .create_inflection_ai_credential_dto import CreateInflectionAICredentialDTO
from .create_inflection_ai_credential_dto_provider import CreateInflectionAICredentialDTOProvider
from .create_langfuse_credential_dto import CreateLangfuseCredentialDTO
from .create_langfuse_credential_dto_provider import CreateLangfuseCredentialDTOProvider
from .create_lmnt_credential_dto import CreateLmntCredentialDTO
from .create_lmnt_credential_dto_provider import CreateLmntCredentialDTOProvider
from .create_make_credential_dto import CreateMakeCredentialDTO
from .create_make_credential_dto_provider import CreateMakeCredentialDTOProvider
from .create_make_tool_dto import CreateMakeToolDTO
from .create_make_tool_dto_type import CreateMakeToolDTOType
from .create_mistral_credential_dto import CreateMistralCredentialDTO
from .create_mistral_credential_dto_provider import CreateMistralCredentialDTOProvider
from .create_neuphonic_credential_dto import CreateNeuphonicCredentialDTO
from .create_neuphonic_credential_dto_provider import CreateNeuphonicCredentialDTOProvider
from .create_open_ai_credential_dto import CreateOpenAICredentialDTO
from .create_open_ai_credential_dto_provider import CreateOpenAICredentialDTOProvider
from .create_open_router_credential_dto import CreateOpenRouterCredentialDTO
from .create_open_router_credential_dto_provider import CreateOpenRouterCredentialDTOProvider
from .create_org_dto import CreateOrgDTO
from .create_org_dto_channel import CreateOrgDTOChannel
from .create_outbound_call_dto import CreateOutboundCallDTO
from .create_output_tool_dto import CreateOutputToolDTO
from .create_output_tool_dto_type import CreateOutputToolDTOType
from .create_perplexity_ai_credential_dto import CreatePerplexityAICredentialDTO
from .create_perplexity_ai_credential_dto_provider import CreatePerplexityAICredentialDTOProvider
from .create_play_ht_credential_dto import CreatePlayHTCredentialDTO
from .create_play_ht_credential_dto_provider import CreatePlayHTCredentialDTOProvider
from .create_query_tool_dto import CreateQueryToolDTO
from .create_query_tool_dto_type import CreateQueryToolDTOType
from .create_rime_ai_credential_dto import CreateRimeAICredentialDTO
from .create_rime_ai_credential_dto_provider import CreateRimeAICredentialDTOProvider
from .create_runpod_credential_dto import CreateRunpodCredentialDTO
from .create_runpod_credential_dto_provider import CreateRunpodCredentialDTOProvider
from .create_s3_credential_dto import CreateS3CredentialDTO
from .create_s3_credential_dto_provider import CreateS3CredentialDTOProvider
from .create_smallest_ai_credential_dto import CreateSmallestAICredentialDTO
from .create_smallest_ai_credential_dto_provider import CreateSmallestAICredentialDTOProvider
from .create_speechmatics_credential_dto import CreateSpeechmaticsCredentialDTO
from .create_speechmatics_credential_dto_provider import CreateSpeechmaticsCredentialDTOProvider
from .create_squad_dto import CreateSquadDTO
from .create_supabase_credential_dto import CreateSupabaseCredentialDTO
from .create_supabase_credential_dto_provider import CreateSupabaseCredentialDTOProvider
from .create_tavus_credential_dto import CreateTavusCredentialDTO
from .create_tavus_credential_dto_provider import CreateTavusCredentialDTOProvider
from .create_telnyx_phone_number_dto import CreateTelnyxPhoneNumberDTO
from .create_telnyx_phone_number_dto_provider import CreateTelnyxPhoneNumberDTOProvider
from .create_test_suite_dto import CreateTestSuiteDto
from .create_test_suite_run_dto import CreateTestSuiteRunDto
from .create_test_suite_test_voice_dto import CreateTestSuiteTestVoiceDto
from .create_test_suite_test_voice_dto_type import CreateTestSuiteTestVoiceDtoType
from .create_text_editor_tool_dto import CreateTextEditorToolDTO
from .create_text_editor_tool_dto_name import CreateTextEditorToolDTOName
from .create_text_editor_tool_dto_sub_type import CreateTextEditorToolDTOSubType
from .create_text_editor_tool_dto_type import CreateTextEditorToolDTOType
from .create_together_ai_credential_dto import CreateTogetherAICredentialDTO
from .create_together_ai_credential_dto_provider import CreateTogetherAICredentialDTOProvider
from .create_token_dto import CreateTokenDTO
from .create_token_dto_tag import CreateTokenDTOTag
from .create_tool_template_dto import CreateToolTemplateDTO
from .create_tool_template_dto_provider import CreateToolTemplateDTOProvider
from .create_tool_template_dto_type import CreateToolTemplateDTOType
from .create_tool_template_dto_visibility import CreateToolTemplateDTOVisibility
from .create_transfer_call_tool_dto import CreateTransferCallToolDTO
from .create_transfer_call_tool_dto_type import CreateTransferCallToolDTOType
from .create_trieve_credential_dto import CreateTrieveCredentialDTO
from .create_trieve_credential_dto_provider import CreateTrieveCredentialDTOProvider
from .create_trieve_knowledge_base_dto import CreateTrieveKnowledgeBaseDTO
from .create_trieve_knowledge_base_dto_provider import CreateTrieveKnowledgeBaseDTOProvider
from .create_twilio_credential_dto import CreateTwilioCredentialDTO
from .create_twilio_credential_dto_provider import CreateTwilioCredentialDTOProvider
from .create_twilio_phone_number_dto import CreateTwilioPhoneNumberDTO
from .create_twilio_phone_number_dto_provider import CreateTwilioPhoneNumberDTOProvider
from .create_vapi_phone_number_dto import CreateVapiPhoneNumberDTO
from .create_vapi_phone_number_dto_provider import CreateVapiPhoneNumberDTOProvider
from .create_voicemail_tool_dto import CreateVoicemailToolDTO
from .create_voicemail_tool_dto_type import CreateVoicemailToolDTOType
from .create_vonage_credential_dto import CreateVonageCredentialDTO
from .create_vonage_credential_dto_provider import CreateVonageCredentialDTOProvider
from .create_vonage_phone_number_dto import CreateVonagePhoneNumberDTO
from .create_vonage_phone_number_dto_provider import CreateVonagePhoneNumberDTOProvider
from .create_web_call_dto import CreateWebCallDTO
from .create_webhook_credential_dto import CreateWebhookCredentialDTO
from .create_webhook_credential_dto_provider import CreateWebhookCredentialDTOProvider
from .create_workflow_dto import CreateWorkflowDTO
from .create_x_ai_credential_dto import CreateXAiCredentialDTO
from .create_x_ai_credential_dto_provider import CreateXAiCredentialDTOProvider
from .custom_knowledge_base import CustomKnowledgeBase
from .custom_knowledge_base_provider import CustomKnowledgeBaseProvider
from .custom_llm_credential import CustomLLMCredential
from .custom_llm_credential_provider import CustomLLMCredentialProvider
from .custom_llm_model import CustomLLMModel
from .custom_llm_model_metadata_send_mode import CustomLLMModelMetadataSendMode
from .custom_llm_model_provider import CustomLLMModelProvider
from .custom_message import CustomMessage
from .custom_message_type import CustomMessageType
from .custom_transcriber import CustomTranscriber
from .custom_transcriber_provider import CustomTranscriberProvider
from .custom_voice import CustomVoice
from .custom_voice_provider import CustomVoiceProvider
from .customer_custom_endpointing_rule import CustomerCustomEndpointingRule
from .customer_custom_endpointing_rule_type import CustomerCustomEndpointingRuleType
from .deep_infra_credential import DeepInfraCredential
from .deep_infra_credential_provider import DeepInfraCredentialProvider
from .deep_infra_model import DeepInfraModel
from .deep_infra_model_provider import DeepInfraModelProvider
from .deep_seek_credential import DeepSeekCredential
from .deep_seek_credential_provider import DeepSeekCredentialProvider
from .deep_seek_model import DeepSeekModel
from .deep_seek_model_model import DeepSeekModelModel
from .deep_seek_model_provider import DeepSeekModelProvider
from .deepgram_credential import DeepgramCredential
from .deepgram_credential_provider import DeepgramCredentialProvider
from .deepgram_transcriber import DeepgramTranscriber
from .deepgram_transcriber_language import DeepgramTranscriberLanguage
from .deepgram_transcriber_model_type_0 import DeepgramTranscriberModelType0
from .deepgram_transcriber_provider import DeepgramTranscriberProvider
from .deepgram_voice import DeepgramVoice
from .deepgram_voice_preset_voice_options import DeepgramVoicePresetVoiceOptions
from .deepgram_voice_provider import DeepgramVoiceProvider
from .dtmf_tool import DtmfTool
from .dtmf_tool_type import DtmfToolType
from .edge import Edge
from .edge_metadata import EdgeMetadata
from .eleven_labs_credential import ElevenLabsCredential
from .eleven_labs_credential_provider import ElevenLabsCredentialProvider
from .eleven_labs_transcriber import ElevenLabsTranscriber
from .eleven_labs_transcriber_language import ElevenLabsTranscriberLanguage
from .eleven_labs_transcriber_model import ElevenLabsTranscriberModel
from .eleven_labs_transcriber_provider import ElevenLabsTranscriberProvider
from .eleven_labs_voice import ElevenLabsVoice
from .eleven_labs_voice_model import ElevenLabsVoiceModel
from .eleven_labs_voice_preset_voice_options import ElevenLabsVoicePresetVoiceOptions
from .eleven_labs_voice_provider import ElevenLabsVoiceProvider
from .end_call_tool import EndCallTool
from .end_call_tool_type import EndCallToolType
from .error import Error
from .exact_replacement import ExactReplacement
from .exact_replacement_type import ExactReplacementType
from .failed_edge_condition import FailedEdgeCondition
from .failed_edge_condition_type import FailedEdgeConditionType
from .fallback_azure_voice import FallbackAzureVoice
from .fallback_azure_voice_preset_voice_options import FallbackAzureVoicePresetVoiceOptions
from .fallback_azure_voice_provider import FallbackAzureVoiceProvider
from .fallback_cartesia_voice import FallbackCartesiaVoice
from .fallback_cartesia_voice_language import FallbackCartesiaVoiceLanguage
from .fallback_cartesia_voice_model import FallbackCartesiaVoiceModel
from .fallback_cartesia_voice_provider import FallbackCartesiaVoiceProvider
from .fallback_custom_voice import FallbackCustomVoice
from .fallback_custom_voice_provider import FallbackCustomVoiceProvider
from .fallback_deepgram_voice import FallbackDeepgramVoice
from .fallback_deepgram_voice_preset_voice_options import FallbackDeepgramVoicePresetVoiceOptions
from .fallback_deepgram_voice_provider import FallbackDeepgramVoiceProvider
from .fallback_eleven_labs_voice import FallbackElevenLabsVoice
from .fallback_eleven_labs_voice_model import FallbackElevenLabsVoiceModel
from .fallback_eleven_labs_voice_preset_voice_options import FallbackElevenLabsVoicePresetVoiceOptions
from .fallback_eleven_labs_voice_provider import FallbackElevenLabsVoiceProvider
from .fallback_hume_voice import FallbackHumeVoice
from .fallback_hume_voice_model import FallbackHumeVoiceModel
from .fallback_hume_voice_provider import FallbackHumeVoiceProvider
from .fallback_lmnt_voice import FallbackLMNTVoice
from .fallback_lmnt_voice_preset_voice_options import FallbackLMNTVoicePresetVoiceOptions
from .fallback_lmnt_voice_provider import FallbackLMNTVoiceProvider
from .fallback_neets_voice import FallbackNeetsVoice
from .fallback_neets_voice_preset_voice_options import FallbackNeetsVoicePresetVoiceOptions
from .fallback_neets_voice_provider import FallbackNeetsVoiceProvider
from .fallback_neuphonic_voice import FallbackNeuphonicVoice
from .fallback_neuphonic_voice_language import FallbackNeuphonicVoiceLanguage
from .fallback_neuphonic_voice_model import FallbackNeuphonicVoiceModel
from .fallback_neuphonic_voice_provider import FallbackNeuphonicVoiceProvider
from .fallback_open_ai_voice import FallbackOpenAIVoice
from .fallback_open_ai_voice_provider import FallbackOpenAIVoiceProvider
from .fallback_open_ai_voice_voice_id import FallbackOpenAIVoiceVoiceId
from .fallback_plan import FallbackPlan
from .fallback_play_ht_voice import FallbackPlayHTVoice
from .fallback_play_ht_voice_emotion import FallbackPlayHTVoiceEmotion
from .fallback_play_ht_voice_language import FallbackPlayHTVoiceLanguage
from .fallback_play_ht_voice_model import FallbackPlayHTVoiceModel
from .fallback_play_ht_voice_preset_voice_options import FallbackPlayHTVoicePresetVoiceOptions
from .fallback_play_ht_voice_provider import FallbackPlayHTVoiceProvider
from .fallback_rime_ai_voice import FallbackRimeAIVoice
from .fallback_rime_ai_voice_model import FallbackRimeAIVoiceModel
from .fallback_rime_ai_voice_preset_voice_options import FallbackRimeAIVoicePresetVoiceOptions
from .fallback_rime_ai_voice_provider import FallbackRimeAIVoiceProvider
from .fallback_smallest_ai_voice import FallbackSmallestAIVoice
from .fallback_smallest_ai_voice_model import FallbackSmallestAIVoiceModel
from .fallback_smallest_ai_voice_preset_voice_options import FallbackSmallestAIVoicePresetVoiceOptions
from .fallback_smallest_ai_voice_provider import FallbackSmallestAIVoiceProvider
from .fallback_tavus_voice import FallbackTavusVoice
from .fallback_tavus_voice_preset_voice_options import FallbackTavusVoicePresetVoiceOptions
from .fallback_tavus_voice_provider import FallbackTavusVoiceProvider
from .fallback_vapi_voice import FallbackVapiVoice
from .fallback_vapi_voice_provider import FallbackVapiVoiceProvider
from .fallback_vapi_voice_voice_id import FallbackVapiVoiceVoiceId
from .file import File
from .file_metadata import FileMetadata
from .file_object import FileObject
from .file_status import FileStatus
from .format_plan import FormatPlan
from .format_plan_formatters_enabled import FormatPlanFormattersEnabled
from .function_tool import FunctionTool
from .function_tool_provider_details import FunctionToolProviderDetails
from .function_tool_provider_details_type import FunctionToolProviderDetailsType
from .function_tool_type import FunctionToolType
from .function_tool_with_tool_call import FunctionToolWithToolCall
from .function_tool_with_tool_call_type import FunctionToolWithToolCallType
from .gather import Gather
from .gather_metadata import GatherMetadata
from .gather_type import GatherType
from .gcp_credential import GcpCredential
from .gcp_credential_provider import GcpCredentialProvider
from .gcp_key import GcpKey
from .gemini_multimodal_live_prebuilt_voice_config import GeminiMultimodalLivePrebuiltVoiceConfig
from .gemini_multimodal_live_prebuilt_voice_config_voice_name import GeminiMultimodalLivePrebuiltVoiceConfigVoiceName
from .gemini_multimodal_live_speech_config import GeminiMultimodalLiveSpeechConfig
from .gemini_multimodal_live_voice_config import GeminiMultimodalLiveVoiceConfig
from .ghl_tool import GhlTool
from .ghl_tool_metadata import GhlToolMetadata
from .ghl_tool_provider_details import GhlToolProviderDetails
from .ghl_tool_provider_details_type import GhlToolProviderDetailsType
from .ghl_tool_type import GhlToolType
from .ghl_tool_with_tool_call import GhlToolWithToolCall
from .ghl_tool_with_tool_call_type import GhlToolWithToolCallType
from .gladia_credential import GladiaCredential
from .gladia_credential_provider import GladiaCredentialProvider
from .gladia_transcriber import GladiaTranscriber
from .gladia_transcriber_language import GladiaTranscriberLanguage
from .gladia_transcriber_language_behaviour_type_0 import GladiaTranscriberLanguageBehaviourType0
from .gladia_transcriber_model_type_0 import GladiaTranscriberModelType0
from .gladia_transcriber_provider import GladiaTranscriberProvider
from .go_high_level_credential import GoHighLevelCredential
from .go_high_level_credential_provider import GoHighLevelCredentialProvider
from .google_credential import GoogleCredential
from .google_credential_provider import GoogleCredentialProvider
from .google_model import GoogleModel
from .google_model_model import GoogleModelModel
from .google_model_provider import GoogleModelProvider
from .google_realtime_config import GoogleRealtimeConfig
from .google_voicemail_detection_plan import GoogleVoicemailDetectionPlan
from .google_voicemail_detection_plan_provider import GoogleVoicemailDetectionPlanProvider
from .groq_credential import GroqCredential
from .groq_credential_provider import GroqCredentialProvider
from .groq_model import GroqModel
from .groq_model_model import GroqModelModel
from .groq_model_provider import GroqModelProvider
from .hangup import Hangup
from .hangup_metadata import HangupMetadata
from .hangup_type import HangupType
from .hook import Hook
from .hook_on import HookOn
from .hume_credential import HumeCredential
from .hume_credential_provider import HumeCredentialProvider
from .hume_voice import HumeVoice
from .hume_voice_model import HumeVoiceModel
from .hume_voice_provider import HumeVoiceProvider
from .import_twilio_phone_number_dto import ImportTwilioPhoneNumberDTO
from .import_vonage_phone_number_dto import ImportVonagePhoneNumberDTO
from .inflection_ai_credential import InflectionAICredential
from .inflection_ai_credential_provider import InflectionAICredentialProvider
from .inflection_ai_model import InflectionAIModel
from .inflection_ai_model_model import InflectionAIModelModel
from .inflection_ai_model_provider import InflectionAIModelProvider
from .invite_user_dto import InviteUserDTO
from .invite_user_dto_role import InviteUserDTORole
from .invoice_plan import InvoicePlan
from .json_schema import JsonSchema
from .json_schema_items import JsonSchemaItems
from .json_schema_properties import JsonSchemaProperties
from .json_schema_type import JsonSchemaType
from .keypad_input_plan import KeypadInputPlan
from .keypad_input_plan_delimiters import KeypadInputPlanDelimiters
from .knowledge_base import KnowledgeBase
from .knowledge_base_model import KnowledgeBaseModel
from .knowledge_base_provider import KnowledgeBaseProvider
from .knowledge_base_response_document import KnowledgeBaseResponseDocument
from .langfuse_credential import LangfuseCredential
from .langfuse_credential_provider import LangfuseCredentialProvider
from .langfuse_observability_plan import LangfuseObservabilityPlan
from .langfuse_observability_plan_provider import LangfuseObservabilityPlanProvider
from .lmnt_credential import LmntCredential
from .lmnt_credential_provider import LmntCredentialProvider
from .lmnt_voice import LMNTVoice
from .lmnt_voice_preset_voice_options import LMNTVoicePresetVoiceOptions
from .lmnt_voice_provider import LMNTVoiceProvider
from .log import Log
from .log_request_body import LogRequestBody
from .log_request_headers import LogRequestHeaders
from .log_request_http_method import LogRequestHttpMethod
from .log_resource import LogResource
from .log_response_body import LogResponseBody
from .log_type import LogType
from .logging_controller_logs_delete_query_type import LoggingControllerLogsDeleteQueryType
from .logging_controller_logs_query_sort_order import LoggingControllerLogsQuerySortOrder
from .logging_controller_logs_query_type import LoggingControllerLogsQueryType
from .logic_edge_condition import LogicEdgeCondition
from .logic_edge_condition_type import LogicEdgeConditionType
from .logs_paginated_response import LogsPaginatedResponse
from .make_credential import MakeCredential
from .make_credential_provider import MakeCredentialProvider
from .make_tool import MakeTool
from .make_tool_metadata import MakeToolMetadata
from .make_tool_provider_details import MakeToolProviderDetails
from .make_tool_provider_details_type import MakeToolProviderDetailsType
from .make_tool_type import MakeToolType
from .make_tool_with_tool_call import MakeToolWithToolCall
from .make_tool_with_tool_call_type import MakeToolWithToolCallType
from .message_plan import MessagePlan
from .metrics import Metrics
from .metrics_bill_daily_breakdown import MetricsBillDailyBreakdown
from .metrics_call_count_daily_breakdown import MetricsCallCountDailyBreakdown
from .metrics_call_minutes_average_daily_breakdown import MetricsCallMinutesAverageDailyBreakdown
from .metrics_call_minutes_daily_breakdown import MetricsCallMinutesDailyBreakdown
from .mistral_credential import MistralCredential
from .mistral_credential_provider import MistralCredentialProvider
from .model_cost import ModelCost
from .model_cost_model import ModelCostModel
from .model_cost_type import ModelCostType
from .monitor import Monitor
from .monitor_plan import MonitorPlan
from .neets_voice import NeetsVoice
from .neets_voice_preset_voice_options import NeetsVoicePresetVoiceOptions
from .neets_voice_provider import NeetsVoiceProvider
from .neuphonic_credential import NeuphonicCredential
from .neuphonic_credential_provider import NeuphonicCredentialProvider
from .neuphonic_voice import NeuphonicVoice
from .neuphonic_voice_language import NeuphonicVoiceLanguage
from .neuphonic_voice_model import NeuphonicVoiceModel
from .neuphonic_voice_provider import NeuphonicVoiceProvider
from .o_auth_2_authentication_plan import OAuth2AuthenticationPlan
from .o_auth_2_authentication_plan_type import OAuth2AuthenticationPlanType
from .oauth_2_authentication_session import Oauth2AuthenticationSession
from .open_ai_credential import OpenAICredential
from .open_ai_credential_provider import OpenAICredentialProvider
from .open_ai_function import OpenAIFunction
from .open_ai_function_parameters import OpenAIFunctionParameters
from .open_ai_function_parameters_properties import OpenAIFunctionParametersProperties
from .open_ai_function_parameters_type import OpenAIFunctionParametersType
from .open_ai_message import OpenAIMessage
from .open_ai_message_role import OpenAIMessageRole
from .open_ai_model import OpenAIModel
from .open_ai_model_fallback_models import OpenAIModelFallbackModels
from .open_ai_model_model import OpenAIModelModel
from .open_ai_model_provider import OpenAIModelProvider
from .open_ai_voice import OpenAIVoice
from .open_ai_voice_provider import OpenAIVoiceProvider
from .open_ai_voice_voice_id import OpenAIVoiceVoiceId
from .open_ai_voicemail_detection_plan import OpenAIVoicemailDetectionPlan
from .open_ai_voicemail_detection_plan_provider import OpenAIVoicemailDetectionPlanProvider
from .open_router_credential import OpenRouterCredential
from .open_router_credential_provider import OpenRouterCredentialProvider
from .open_router_model import OpenRouterModel
from .open_router_model_provider import OpenRouterModelProvider
from .org import Org
from .org_channel import OrgChannel
from .org_plan import OrgPlan
from .org_plan_included_providers_item import OrgPlanIncludedProvidersItem
from .output_tool import OutputTool
from .output_tool_type import OutputToolType
from .pagination_meta import PaginationMeta
from .perplexity_ai_credential import PerplexityAICredential
from .perplexity_ai_credential_provider import PerplexityAICredentialProvider
from .perplexity_ai_model import PerplexityAIModel
from .perplexity_ai_model_provider import PerplexityAIModelProvider
from .phone_number_paginated_response import PhoneNumberPaginatedResponse
from .play_ht_credential import PlayHTCredential
from .play_ht_credential_provider import PlayHTCredentialProvider
from .play_ht_voice import PlayHTVoice
from .play_ht_voice_emotion import PlayHTVoiceEmotion
from .play_ht_voice_language import PlayHTVoiceLanguage
from .play_ht_voice_model import PlayHTVoiceModel
from .play_ht_voice_preset_voice_options import PlayHTVoicePresetVoiceOptions
from .play_ht_voice_provider import PlayHTVoiceProvider
from .query_tool import QueryTool
from .query_tool_type import QueryToolType
from .regex_option import RegexOption
from .regex_option_type import RegexOptionType
from .regex_replacement import RegexReplacement
from .regex_replacement_type import RegexReplacementType
from .rime_ai_credential import RimeAICredential
from .rime_ai_credential_provider import RimeAICredentialProvider
from .rime_ai_voice import RimeAIVoice
from .rime_ai_voice_model import RimeAIVoiceModel
from .rime_ai_voice_preset_voice_options import RimeAIVoicePresetVoiceOptions
from .rime_ai_voice_provider import RimeAIVoiceProvider
from .runpod_credential import RunpodCredential
from .runpod_credential_provider import RunpodCredentialProvider
from .s3_credential import S3Credential
from .s3_credential_provider import S3CredentialProvider
from .say import Say
from .say_hook import SayHook
from .say_hook_metadata import SayHookMetadata
from .say_hook_type import SayHookType
from .say_metadata import SayMetadata
from .say_type import SayType
from .sbc_configuration import SbcConfiguration
from .server import Server
from .server_headers import ServerHeaders
from .server_message import ServerMessage
from .server_message_assistant_request import ServerMessageAssistantRequest
from .server_message_assistant_request_type import ServerMessageAssistantRequestType
from .server_message_conversation_update import ServerMessageConversationUpdate
from .server_message_conversation_update_type import ServerMessageConversationUpdateType
from .server_message_end_of_call_report import ServerMessageEndOfCallReport
from .server_message_end_of_call_report_ended_reason import ServerMessageEndOfCallReportEndedReason
from .server_message_end_of_call_report_type import ServerMessageEndOfCallReportType
from .server_message_hang import ServerMessageHang
from .server_message_hang_type import ServerMessageHangType
from .server_message_knowledge_base_request import ServerMessageKnowledgeBaseRequest
from .server_message_knowledge_base_request_type import ServerMessageKnowledgeBaseRequestType
from .server_message_language_change_detected import ServerMessageLanguageChangeDetected
from .server_message_language_change_detected_type import ServerMessageLanguageChangeDetectedType
from .server_message_model_output import ServerMessageModelOutput
from .server_message_model_output_output import ServerMessageModelOutputOutput
from .server_message_model_output_type import ServerMessageModelOutputType
from .server_message_phone_call_control import ServerMessagePhoneCallControl
from .server_message_phone_call_control_request import ServerMessagePhoneCallControlRequest
from .server_message_phone_call_control_type import ServerMessagePhoneCallControlType
from .server_message_response import ServerMessageResponse
from .server_message_response_assistant_request import ServerMessageResponseAssistantRequest
from .server_message_response_knowledge_base_request import ServerMessageResponseKnowledgeBaseRequest
from .server_message_response_tool_calls import ServerMessageResponseToolCalls
from .server_message_response_transfer_destination_request import ServerMessageResponseTransferDestinationRequest
from .server_message_response_voice_request import ServerMessageResponseVoiceRequest
from .server_message_speech_update import ServerMessageSpeechUpdate
from .server_message_speech_update_role import ServerMessageSpeechUpdateRole
from .server_message_speech_update_status import ServerMessageSpeechUpdateStatus
from .server_message_speech_update_type import ServerMessageSpeechUpdateType
from .server_message_status_update import ServerMessageStatusUpdate
from .server_message_status_update_ended_reason import ServerMessageStatusUpdateEndedReason
from .server_message_status_update_inbound_phone_call_debugging_artifacts import (
    ServerMessageStatusUpdateInboundPhoneCallDebuggingArtifacts,
)
from .server_message_status_update_status import ServerMessageStatusUpdateStatus
from .server_message_status_update_type import ServerMessageStatusUpdateType
from .server_message_tool_calls import ServerMessageToolCalls
from .server_message_tool_calls_type import ServerMessageToolCallsType
from .server_message_transcript import ServerMessageTranscript
from .server_message_transcript_role import ServerMessageTranscriptRole
from .server_message_transcript_transcript_type import ServerMessageTranscriptTranscriptType
from .server_message_transcript_type import ServerMessageTranscriptType
from .server_message_transfer_destination_request import ServerMessageTransferDestinationRequest
from .server_message_transfer_destination_request_type import ServerMessageTransferDestinationRequestType
from .server_message_transfer_update import ServerMessageTransferUpdate
from .server_message_transfer_update_from_step_record import ServerMessageTransferUpdateFromStepRecord
from .server_message_transfer_update_to_step_record import ServerMessageTransferUpdateToStepRecord
from .server_message_transfer_update_type import ServerMessageTransferUpdateType
from .server_message_user_interrupted import ServerMessageUserInterrupted
from .server_message_user_interrupted_type import ServerMessageUserInterruptedType
from .server_message_voice_input import ServerMessageVoiceInput
from .server_message_voice_input_type import ServerMessageVoiceInputType
from .server_message_voice_request import ServerMessageVoiceRequest
from .server_message_voice_request_type import ServerMessageVoiceRequestType
from .sip_authentication import SipAuthentication
from .sip_trunk_gateway import SipTrunkGateway
from .sip_trunk_gateway_outbound_protocol import SipTrunkGatewayOutboundProtocol
from .sip_trunk_outbound_authentication_plan import SipTrunkOutboundAuthenticationPlan
from .sip_trunk_outbound_sip_register_plan import SipTrunkOutboundSipRegisterPlan
from .smallest_ai_credential import SmallestAICredential
from .smallest_ai_credential_provider import SmallestAICredentialProvider
from .smallest_ai_voice import SmallestAIVoice
from .smallest_ai_voice_model import SmallestAIVoiceModel
from .smallest_ai_voice_preset_voice_options import SmallestAIVoicePresetVoiceOptions
from .smallest_ai_voice_provider import SmallestAIVoiceProvider
from .speechmatics_credential import SpeechmaticsCredential
from .speechmatics_credential_provider import SpeechmaticsCredentialProvider
from .speechmatics_transcriber import SpeechmaticsTranscriber
from .speechmatics_transcriber_language import SpeechmaticsTranscriberLanguage
from .speechmatics_transcriber_model import SpeechmaticsTranscriberModel
from .speechmatics_transcriber_provider import SpeechmaticsTranscriberProvider
from .squad import Squad
from .squad_member_dto import SquadMemberDTO
from .start_speaking_plan import StartSpeakingPlan
from .start_speaking_plan_smart_endpointing_enabled_type_1 import StartSpeakingPlanSmartEndpointingEnabledType1
from .stop_speaking_plan import StopSpeakingPlan
from .structured_data_plan import StructuredDataPlan
from .structured_data_plan_messages_item import StructuredDataPlanMessagesItem
from .subscription import Subscription
from .subscription_status import SubscriptionStatus
from .subscription_type import SubscriptionType
from .success_evaluation_plan import SuccessEvaluationPlan
from .success_evaluation_plan_messages_item import SuccessEvaluationPlanMessagesItem
from .success_evaluation_plan_rubric import SuccessEvaluationPlanRubric
from .summary_plan import SummaryPlan
from .summary_plan_messages_item import SummaryPlanMessagesItem
from .supabase_bucket_plan import SupabaseBucketPlan
from .supabase_bucket_plan_region import SupabaseBucketPlanRegion
from .supabase_credential import SupabaseCredential
from .supabase_credential_provider import SupabaseCredentialProvider
from .sync_voice_library_dto import SyncVoiceLibraryDTO
from .sync_voice_library_dto_providers import SyncVoiceLibraryDTOProviders
from .system_message import SystemMessage
from .talkscriber_transcriber import TalkscriberTranscriber
from .talkscriber_transcriber_language import TalkscriberTranscriberLanguage
from .talkscriber_transcriber_model import TalkscriberTranscriberModel
from .talkscriber_transcriber_provider import TalkscriberTranscriberProvider
from .tavus_conversation_properties import TavusConversationProperties
from .tavus_credential import TavusCredential
from .tavus_credential_provider import TavusCredentialProvider
from .tavus_voice import TavusVoice
from .tavus_voice_preset_voice_options import TavusVoicePresetVoiceOptions
from .tavus_voice_provider import TavusVoiceProvider
from .telnyx_phone_number import TelnyxPhoneNumber
from .telnyx_phone_number_provider import TelnyxPhoneNumberProvider
from .telnyx_phone_number_status import TelnyxPhoneNumberStatus
from .template import Template
from .template_provider import TemplateProvider
from .template_type import TemplateType
from .template_visibility import TemplateVisibility
from .test_suite import TestSuite
from .test_suite_controller_find_all_paginated_sort_order import TestSuiteControllerFindAllPaginatedSortOrder
from .test_suite_run import TestSuiteRun
from .test_suite_run_controller_find_all_paginated_sort_order import TestSuiteRunControllerFindAllPaginatedSortOrder
from .test_suite_run_scorer_ai import TestSuiteRunScorerAI
from .test_suite_run_scorer_ai_result import TestSuiteRunScorerAIResult
from .test_suite_run_scorer_ai_type import TestSuiteRunScorerAIType
from .test_suite_run_status import TestSuiteRunStatus
from .test_suite_run_test_attempt import TestSuiteRunTestAttempt
from .test_suite_run_test_attempt_call import TestSuiteRunTestAttemptCall
from .test_suite_run_test_result import TestSuiteRunTestResult
from .test_suite_runs_paginated_response import TestSuiteRunsPaginatedResponse
from .test_suite_test_controller_find_all_paginated_sort_order import TestSuiteTestControllerFindAllPaginatedSortOrder
from .test_suite_test_scorer_ai import TestSuiteTestScorerAI
from .test_suite_test_scorer_ai_type import TestSuiteTestScorerAIType
from .test_suite_test_voice import TestSuiteTestVoice
from .test_suite_test_voice_type import TestSuiteTestVoiceType
from .test_suite_tests_paginated_response import TestSuiteTestsPaginatedResponse
from .test_suites_paginated_response import TestSuitesPaginatedResponse
from .text_content import TextContent
from .text_content_language import TextContentLanguage
from .text_content_type import TextContentType
from .text_editor_tool import TextEditorTool
from .text_editor_tool_name import TextEditorToolName
from .text_editor_tool_sub_type import TextEditorToolSubType
from .text_editor_tool_type import TextEditorToolType
from .text_editor_tool_with_tool_call import TextEditorToolWithToolCall
from .text_editor_tool_with_tool_call_name import TextEditorToolWithToolCallName
from .text_editor_tool_with_tool_call_sub_type import TextEditorToolWithToolCallSubType
from .text_editor_tool_with_tool_call_type import TextEditorToolWithToolCallType
from .time_range import TimeRange
from .time_range_step import TimeRangeStep
from .together_ai_credential import TogetherAICredential
from .together_ai_credential_provider import TogetherAICredentialProvider
from .together_ai_model import TogetherAIModel
from .together_ai_model_provider import TogetherAIModelProvider
from .token import Token
from .token_restrictions import TokenRestrictions
from .token_tag import TokenTag
from .tool_call import ToolCall
from .tool_call_function import ToolCallFunction
from .tool_call_function_arguments import ToolCallFunctionArguments
from .tool_call_message import ToolCallMessage
from .tool_call_message_tool_calls_item import ToolCallMessageToolCallsItem
from .tool_call_result import ToolCallResult
from .tool_call_result_message import ToolCallResultMessage
from .tool_call_type import ToolCallType
from .tool_message_complete import ToolMessageComplete
from .tool_message_complete_role import ToolMessageCompleteRole
from .tool_message_complete_type import ToolMessageCompleteType
from .tool_message_delayed import ToolMessageDelayed
from .tool_message_delayed_type import ToolMessageDelayedType
from .tool_message_failed import ToolMessageFailed
from .tool_message_failed_type import ToolMessageFailedType
from .tool_message_start import ToolMessageStart
from .tool_message_start_type import ToolMessageStartType
from .tool_template_metadata import ToolTemplateMetadata
from .tool_template_setup import ToolTemplateSetup
from .transcriber_cost import TranscriberCost
from .transcriber_cost_transcriber import TranscriberCostTranscriber
from .transcriber_cost_type import TranscriberCostType
from .transcript_plan import TranscriptPlan
from .transcription_endpointing_plan import TranscriptionEndpointingPlan
from .transfer import Transfer
from .transfer_assistant_hook_action import TransferAssistantHookAction
from .transfer_assistant_hook_action_type import TransferAssistantHookActionType
from .transfer_call_tool import TransferCallTool
from .transfer_call_tool_type import TransferCallToolType
from .transfer_destination import TransferDestination
from .transfer_destination_assistant import TransferDestinationAssistant
from .transfer_destination_assistant_transfer_mode import TransferDestinationAssistantTransferMode
from .transfer_destination_assistant_type import TransferDestinationAssistantType
from .transfer_destination_number import TransferDestinationNumber
from .transfer_destination_number_type import TransferDestinationNumberType
from .transfer_destination_sip import TransferDestinationSip
from .transfer_destination_sip_sip_headers import TransferDestinationSipSipHeaders
from .transfer_destination_sip_type import TransferDestinationSipType
from .transfer_destination_step import TransferDestinationStep
from .transfer_destination_step_type import TransferDestinationStepType
from .transfer_metadata import TransferMetadata
from .transfer_plan import TransferPlan
from .transfer_plan_mode import TransferPlanMode
from .transfer_plan_sip_verb import TransferPlanSipVerb
from .transfer_type import TransferType
from .transport import Transport
from .transport_configuration_twilio import TransportConfigurationTwilio
from .transport_configuration_twilio_provider import TransportConfigurationTwilioProvider
from .transport_configuration_twilio_recording_channels import TransportConfigurationTwilioRecordingChannels
from .transport_cost import TransportCost
from .transport_cost_provider import TransportCostProvider
from .transport_cost_type import TransportCostType
from .transport_provider import TransportProvider
from .trieve_credential import TrieveCredential
from .trieve_credential_provider import TrieveCredentialProvider
from .trieve_knowledge_base import TrieveKnowledgeBase
from .trieve_knowledge_base_chunk_plan import TrieveKnowledgeBaseChunkPlan
from .trieve_knowledge_base_create import TrieveKnowledgeBaseCreate
from .trieve_knowledge_base_create_type import TrieveKnowledgeBaseCreateType
from .trieve_knowledge_base_import import TrieveKnowledgeBaseImport
from .trieve_knowledge_base_import_type import TrieveKnowledgeBaseImportType
from .trieve_knowledge_base_provider import TrieveKnowledgeBaseProvider
from .trieve_knowledge_base_search_plan import TrieveKnowledgeBaseSearchPlan
from .trieve_knowledge_base_search_plan_search_type import TrieveKnowledgeBaseSearchPlanSearchType
from .twilio_credential import TwilioCredential
from .twilio_credential_provider import TwilioCredentialProvider
from .twilio_phone_number import TwilioPhoneNumber
from .twilio_phone_number_provider import TwilioPhoneNumberProvider
from .twilio_phone_number_status import TwilioPhoneNumberStatus
from .twilio_voicemail_detection_plan import TwilioVoicemailDetectionPlan
from .twilio_voicemail_detection_plan_provider import TwilioVoicemailDetectionPlanProvider
from .twilio_voicemail_detection_plan_voicemail_detection_types import (
    TwilioVoicemailDetectionPlanVoicemailDetectionTypes,
)
from .update_anthropic_credential_dto import UpdateAnthropicCredentialDTO
from .update_anyscale_credential_dto import UpdateAnyscaleCredentialDTO
from .update_assembly_ai_credential_dto import UpdateAssemblyAICredentialDTO
from .update_assistant_dto import UpdateAssistantDTO
from .update_assistant_dto_background_sound import UpdateAssistantDTOBackgroundSound
from .update_assistant_dto_client_messages import UpdateAssistantDTOClientMessages
from .update_assistant_dto_first_message_mode import UpdateAssistantDTOFirstMessageMode
from .update_assistant_dto_metadata import UpdateAssistantDTOMetadata
from .update_assistant_dto_server_messages import UpdateAssistantDTOServerMessages
from .update_azure_credential_dto import UpdateAzureCredentialDTO
from .update_azure_credential_dto_region import UpdateAzureCredentialDTORegion
from .update_azure_credential_dto_service import UpdateAzureCredentialDTOService
from .update_azure_open_ai_credential_dto import UpdateAzureOpenAICredentialDTO
from .update_azure_open_ai_credential_dto_models import UpdateAzureOpenAICredentialDTOModels
from .update_azure_open_ai_credential_dto_region import UpdateAzureOpenAICredentialDTORegion
from .update_bash_tool_dto import UpdateBashToolDTO
from .update_bash_tool_dto_name import UpdateBashToolDTOName
from .update_bash_tool_dto_sub_type import UpdateBashToolDTOSubType
from .update_byo_phone_number_dto import UpdateByoPhoneNumberDTO
from .update_byo_sip_trunk_credential_dto import UpdateByoSipTrunkCredentialDTO
from .update_call_dto import UpdateCallDTO
from .update_cartesia_credential_dto import UpdateCartesiaCredentialDTO
from .update_cerebras_credential_dto import UpdateCerebrasCredentialDTO
from .update_cloudflare_credential_dto import UpdateCloudflareCredentialDTO
from .update_computer_tool_dto import UpdateComputerToolDTO
from .update_computer_tool_dto_name import UpdateComputerToolDTOName
from .update_computer_tool_dto_sub_type import UpdateComputerToolDTOSubType
from .update_custom_knowledge_base_dto import UpdateCustomKnowledgeBaseDTO
from .update_custom_llm_credential_dto import UpdateCustomLLMCredentialDTO
from .update_deep_infra_credential_dto import UpdateDeepInfraCredentialDTO
from .update_deep_seek_credential_dto import UpdateDeepSeekCredentialDTO
from .update_deepgram_credential_dto import UpdateDeepgramCredentialDTO
from .update_dtmf_tool_dto import UpdateDtmfToolDTO
from .update_eleven_labs_credential_dto import UpdateElevenLabsCredentialDTO
from .update_end_call_tool_dto import UpdateEndCallToolDTO
from .update_file_dto import UpdateFileDTO
from .update_function_tool_dto import UpdateFunctionToolDTO
from .update_gcp_credential_dto import UpdateGcpCredentialDTO
from .update_ghl_tool_dto import UpdateGhlToolDTO
from .update_gladia_credential_dto import UpdateGladiaCredentialDTO
from .update_go_high_level_credential_dto import UpdateGoHighLevelCredentialDTO
from .update_google_credential_dto import UpdateGoogleCredentialDTO
from .update_groq_credential_dto import UpdateGroqCredentialDTO
from .update_hume_credential_dto import UpdateHumeCredentialDTO
from .update_inflection_ai_credential_dto import UpdateInflectionAICredentialDTO
from .update_langfuse_credential_dto import UpdateLangfuseCredentialDTO
from .update_lmnt_credential_dto import UpdateLmntCredentialDTO
from .update_make_credential_dto import UpdateMakeCredentialDTO
from .update_make_tool_dto import UpdateMakeToolDTO
from .update_mistral_credential_dto import UpdateMistralCredentialDTO
from .update_neuphonic_credential_dto import UpdateNeuphonicCredentialDTO
from .update_open_ai_credential_dto import UpdateOpenAICredentialDTO
from .update_open_router_credential_dto import UpdateOpenRouterCredentialDTO
from .update_org_dto import UpdateOrgDTO
from .update_org_dto_channel import UpdateOrgDTOChannel
from .update_output_tool_dto import UpdateOutputToolDTO
from .update_perplexity_ai_credential_dto import UpdatePerplexityAICredentialDTO
from .update_play_ht_credential_dto import UpdatePlayHTCredentialDTO
from .update_query_tool_dto import UpdateQueryToolDTO
from .update_rime_ai_credential_dto import UpdateRimeAICredentialDTO
from .update_runpod_credential_dto import UpdateRunpodCredentialDTO
from .update_s3_credential_dto import UpdateS3CredentialDTO
from .update_smallest_ai_credential_dto import UpdateSmallestAICredentialDTO
from .update_speechmatics_credential_dto import UpdateSpeechmaticsCredentialDTO
from .update_squad_dto import UpdateSquadDTO
from .update_supabase_credential_dto import UpdateSupabaseCredentialDTO
from .update_tavus_credential_dto import UpdateTavusCredentialDTO
from .update_telnyx_phone_number_dto import UpdateTelnyxPhoneNumberDTO
from .update_test_suite_dto import UpdateTestSuiteDto
from .update_test_suite_run_dto import UpdateTestSuiteRunDto
from .update_test_suite_test_voice_dto import UpdateTestSuiteTestVoiceDto
from .update_text_editor_tool_dto import UpdateTextEditorToolDTO
from .update_text_editor_tool_dto_name import UpdateTextEditorToolDTOName
from .update_text_editor_tool_dto_sub_type import UpdateTextEditorToolDTOSubType
from .update_together_ai_credential_dto import UpdateTogetherAICredentialDTO
from .update_token_dto import UpdateTokenDTO
from .update_token_dto_tag import UpdateTokenDTOTag
from .update_tool_template_dto import UpdateToolTemplateDTO
from .update_tool_template_dto_provider import UpdateToolTemplateDTOProvider
from .update_tool_template_dto_type import UpdateToolTemplateDTOType
from .update_tool_template_dto_visibility import UpdateToolTemplateDTOVisibility
from .update_transfer_call_tool_dto import UpdateTransferCallToolDTO
from .update_trieve_credential_dto import UpdateTrieveCredentialDTO
from .update_trieve_knowledge_base_dto import UpdateTrieveKnowledgeBaseDTO
from .update_twilio_credential_dto import UpdateTwilioCredentialDTO
from .update_twilio_phone_number_dto import UpdateTwilioPhoneNumberDTO
from .update_user_role_dto import UpdateUserRoleDTO
from .update_user_role_dto_role import UpdateUserRoleDTORole
from .update_vapi_phone_number_dto import UpdateVapiPhoneNumberDTO
from .update_vonage_credential_dto import UpdateVonageCredentialDTO
from .update_vonage_phone_number_dto import UpdateVonagePhoneNumberDTO
from .update_webhook_credential_dto import UpdateWebhookCredentialDTO
from .update_workflow_dto import UpdateWorkflowDTO
from .update_x_ai_credential_dto import UpdateXAiCredentialDTO
from .user import User
from .user_message import UserMessage
from .vapi_cost import VapiCost
from .vapi_cost_sub_type import VapiCostSubType
from .vapi_cost_type import VapiCostType
from .vapi_model import VapiModel
from .vapi_model_provider import VapiModelProvider
from .vapi_phone_number import VapiPhoneNumber
from .vapi_phone_number_provider import VapiPhoneNumberProvider
from .vapi_phone_number_status import VapiPhoneNumberStatus
from .vapi_voice import VapiVoice
from .vapi_voice_provider import VapiVoiceProvider
from .vapi_voice_voice_id import VapiVoiceVoiceId
from .voice_cost import VoiceCost
from .voice_cost_type import VoiceCostType
from .voice_cost_voice import VoiceCostVoice
from .voice_library import VoiceLibrary
from .voice_library_gender import VoiceLibraryGender
from .voice_library_provider import VoiceLibraryProvider
from .voice_library_voice_response import VoiceLibraryVoiceResponse
from .voice_library_voice_response_age import VoiceLibraryVoiceResponseAge
from .voicemail_detection_cost import VoicemailDetectionCost
from .voicemail_detection_cost_model import VoicemailDetectionCostModel
from .voicemail_detection_cost_provider import VoicemailDetectionCostProvider
from .voicemail_detection_cost_type import VoicemailDetectionCostType
from .vonage_credential import VonageCredential
from .vonage_credential_provider import VonageCredentialProvider
from .vonage_phone_number import VonagePhoneNumber
from .vonage_phone_number_provider import VonagePhoneNumberProvider
from .vonage_phone_number_status import VonagePhoneNumberStatus
from .webhook_credential import WebhookCredential
from .webhook_credential_provider import WebhookCredentialProvider
from .workflow import Workflow
from .x_ai_credential import XAiCredential
from .x_ai_credential_provider import XAiCredentialProvider
from .xai_model import XaiModel
from .xai_model_model import XaiModelModel
from .xai_model_provider import XaiModelProvider

__all__ = (
    "AddVoiceToProviderDTO",
    "AIEdgeCondition",
    "AIEdgeConditionType",
    "Analysis",
    "AnalysisCost",
    "AnalysisCostAnalysisType",
    "AnalysisCostBreakdown",
    "AnalysisCostModel",
    "AnalysisCostType",
    "AnalysisPlan",
    "AnalysisStructuredData",
    "AnalyticsOperation",
    "AnalyticsOperationColumn",
    "AnalyticsOperationOperation",
    "AnalyticsQuery",
    "AnalyticsQueryDTO",
    "AnalyticsQueryGroupBy",
    "AnalyticsQueryResult",
    "AnalyticsQueryResultResultItem",
    "AnalyticsQueryTable",
    "AnthropicCredential",
    "AnthropicCredentialProvider",
    "AnthropicModel",
    "AnthropicModelModel",
    "AnthropicModelProvider",
    "AnthropicThinkingConfig",
    "AnthropicThinkingConfigType",
    "AnyscaleCredential",
    "AnyscaleCredentialProvider",
    "AnyscaleModel",
    "AnyscaleModelProvider",
    "ApiRequest",
    "ApiRequestMetadata",
    "ApiRequestMethod",
    "ApiRequestMode",
    "ApiRequestType",
    "Artifact",
    "ArtifactPlan",
    "AssemblyAICredential",
    "AssemblyAICredentialProvider",
    "AssemblyAITranscriber",
    "AssemblyAITranscriberLanguage",
    "AssemblyAITranscriberProvider",
    "Assistant",
    "AssistantBackgroundSound",
    "AssistantClientMessages",
    "AssistantCustomEndpointingRule",
    "AssistantCustomEndpointingRuleType",
    "AssistantFirstMessageMode",
    "AssistantHookActionBase",
    "AssistantHookFilter",
    "AssistantHookFilterType",
    "AssistantHooks",
    "AssistantHooksOn",
    "AssistantMetadata",
    "AssistantOverrides",
    "AssistantOverridesBackgroundSound",
    "AssistantOverridesClientMessages",
    "AssistantOverridesFirstMessageMode",
    "AssistantOverridesMetadata",
    "AssistantOverridesServerMessages",
    "AssistantOverridesVariableValues",
    "AssistantPaginatedResponse",
    "AssistantServerMessages",
    "AutoReloadPlan",
    "AzureBlobStorageBucketPlan",
    "AzureCredential",
    "AzureCredentialProvider",
    "AzureCredentialRegion",
    "AzureCredentialService",
    "AzureOpenAICredential",
    "AzureOpenAICredentialModels",
    "AzureOpenAICredentialProvider",
    "AzureOpenAICredentialRegion",
    "AzureSpeechTranscriber",
    "AzureSpeechTranscriberLanguage",
    "AzureSpeechTranscriberProvider",
    "AzureVoice",
    "AzureVoicePresetVoiceOptions",
    "AzureVoiceProvider",
    "BackoffPlan",
    "BackoffPlanType",
    "BashTool",
    "BashToolName",
    "BashToolSubType",
    "BashToolType",
    "BashToolWithToolCall",
    "BashToolWithToolCallName",
    "BashToolWithToolCallSubType",
    "BashToolWithToolCallType",
    "BothCustomEndpointingRule",
    "BothCustomEndpointingRuleType",
    "BotMessage",
    "BucketPlan",
    "ByoPhoneNumber",
    "ByoPhoneNumberProvider",
    "ByoPhoneNumberStatus",
    "ByoSipTrunkCredential",
    "ByoSipTrunkCredentialProvider",
    "Call",
    "CallEndedReason",
    "CallLogPrivileged",
    "CallLogPrivilegedLevel",
    "CallLogsPaginatedResponse",
    "CallPaginatedResponse",
    "CallPhoneCallProvider",
    "CallPhoneCallTransport",
    "CallStatus",
    "CallType",
    "CartesiaCredential",
    "CartesiaCredentialProvider",
    "CartesiaExperimentalControls",
    "CartesiaExperimentalControlsEmotion",
    "CartesiaExperimentalControlsSpeed",
    "CartesiaVoice",
    "CartesiaVoiceLanguage",
    "CartesiaVoiceModel",
    "CartesiaVoiceProvider",
    "CerebrasCredential",
    "CerebrasCredentialProvider",
    "CerebrasModel",
    "CerebrasModelModel",
    "CerebrasModelProvider",
    "ChatCompletionMessage",
    "ChatCompletionMessageMetadata",
    "ChatCompletionMessageMetadataTaskState",
    "ChatCompletionMessageRole",
    "ChatCompletionsDTO",
    "ChatServiceResponse",
    "ChunkPlan",
    "ChunkPlanPunctuationBoundaries",
    "ClientInboundMessage",
    "ClientInboundMessageAddMessage",
    "ClientInboundMessageAddMessageType",
    "ClientInboundMessageControl",
    "ClientInboundMessageControlControl",
    "ClientInboundMessageControlType",
    "ClientInboundMessageEndCall",
    "ClientInboundMessageEndCallType",
    "ClientInboundMessageSay",
    "ClientInboundMessageSayType",
    "ClientInboundMessageTransfer",
    "ClientInboundMessageTransferType",
    "ClientMessage",
    "ClientMessageConversationUpdate",
    "ClientMessageConversationUpdateType",
    "ClientMessageHang",
    "ClientMessageHangType",
    "ClientMessageLanguageChangeDetected",
    "ClientMessageLanguageChangeDetectedType",
    "ClientMessageMetadata",
    "ClientMessageMetadataType",
    "ClientMessageModelOutput",
    "ClientMessageModelOutputOutput",
    "ClientMessageModelOutputType",
    "ClientMessageSpeechUpdate",
    "ClientMessageSpeechUpdateRole",
    "ClientMessageSpeechUpdateStatus",
    "ClientMessageSpeechUpdateType",
    "ClientMessageToolCalls",
    "ClientMessageToolCallsResult",
    "ClientMessageToolCallsResultToolCallResult",
    "ClientMessageToolCallsResultType",
    "ClientMessageToolCallsType",
    "ClientMessageTranscript",
    "ClientMessageTranscriptRole",
    "ClientMessageTranscriptTranscriptType",
    "ClientMessageTranscriptType",
    "ClientMessageTransferUpdate",
    "ClientMessageTransferUpdateFromStepRecord",
    "ClientMessageTransferUpdateToStepRecord",
    "ClientMessageTransferUpdateType",
    "ClientMessageUserInterrupted",
    "ClientMessageUserInterruptedType",
    "ClientMessageVoiceInput",
    "ClientMessageVoiceInputType",
    "ClientMessageWorkflowNodeStarted",
    "ClientMessageWorkflowNodeStartedNode",
    "ClientMessageWorkflowNodeStartedType",
    "CloneVoiceDTO",
    "CloudflareCredential",
    "CloudflareCredentialProvider",
    "CloudflareR2BucketPlan",
    "CompliancePlan",
    "ComputerTool",
    "ComputerToolName",
    "ComputerToolSubType",
    "ComputerToolType",
    "ComputerToolWithToolCall",
    "ComputerToolWithToolCallName",
    "ComputerToolWithToolCallSubType",
    "ComputerToolWithToolCallType",
    "Condition",
    "ConditionOperator",
    "ConditionValue",
    "CostBreakdown",
    "CreateAnthropicCredentialDTO",
    "CreateAnthropicCredentialDTOProvider",
    "CreateAnyscaleCredentialDTO",
    "CreateAnyscaleCredentialDTOProvider",
    "CreateAssemblyAICredentialDTO",
    "CreateAssemblyAICredentialDTOProvider",
    "CreateAssistantDTO",
    "CreateAssistantDTOBackgroundSound",
    "CreateAssistantDTOClientMessages",
    "CreateAssistantDTOFirstMessageMode",
    "CreateAssistantDTOMetadata",
    "CreateAssistantDTOServerMessages",
    "CreateAzureCredentialDTO",
    "CreateAzureCredentialDTOProvider",
    "CreateAzureCredentialDTORegion",
    "CreateAzureCredentialDTOService",
    "CreateAzureOpenAICredentialDTO",
    "CreateAzureOpenAICredentialDTOModels",
    "CreateAzureOpenAICredentialDTOProvider",
    "CreateAzureOpenAICredentialDTORegion",
    "CreateBashToolDTO",
    "CreateBashToolDTOName",
    "CreateBashToolDTOSubType",
    "CreateBashToolDTOType",
    "CreateByoPhoneNumberDTO",
    "CreateByoPhoneNumberDTOProvider",
    "CreateByoSipTrunkCredentialDTO",
    "CreateByoSipTrunkCredentialDTOProvider",
    "CreateCallDTO",
    "CreateCartesiaCredentialDTO",
    "CreateCartesiaCredentialDTOProvider",
    "CreateCerebrasCredentialDTO",
    "CreateCerebrasCredentialDTOProvider",
    "CreateCloudflareCredentialDTO",
    "CreateCloudflareCredentialDTOProvider",
    "CreateComputerToolDTO",
    "CreateComputerToolDTOName",
    "CreateComputerToolDTOSubType",
    "CreateComputerToolDTOType",
    "CreateCustomerDTO",
    "CreateCustomKnowledgeBaseDTO",
    "CreateCustomKnowledgeBaseDTOProvider",
    "CreateCustomLLMCredentialDTO",
    "CreateCustomLLMCredentialDTOProvider",
    "CreateDeepgramCredentialDTO",
    "CreateDeepgramCredentialDTOProvider",
    "CreateDeepInfraCredentialDTO",
    "CreateDeepInfraCredentialDTOProvider",
    "CreateDeepSeekCredentialDTO",
    "CreateDeepSeekCredentialDTOProvider",
    "CreateDtmfToolDTO",
    "CreateDtmfToolDTOType",
    "CreateElevenLabsCredentialDTO",
    "CreateElevenLabsCredentialDTOProvider",
    "CreateEndCallToolDTO",
    "CreateEndCallToolDTOType",
    "CreateFileDTO",
    "CreateFunctionToolDTO",
    "CreateFunctionToolDTOType",
    "CreateGcpCredentialDTO",
    "CreateGcpCredentialDTOProvider",
    "CreateGhlToolDTO",
    "CreateGhlToolDTOType",
    "CreateGladiaCredentialDTO",
    "CreateGladiaCredentialDTOProvider",
    "CreateGoHighLevelCredentialDTO",
    "CreateGoHighLevelCredentialDTOProvider",
    "CreateGoogleCredentialDTO",
    "CreateGoogleCredentialDTOProvider",
    "CreateGroqCredentialDTO",
    "CreateGroqCredentialDTOProvider",
    "CreateHumeCredentialDTO",
    "CreateHumeCredentialDTOProvider",
    "CreateInflectionAICredentialDTO",
    "CreateInflectionAICredentialDTOProvider",
    "CreateLangfuseCredentialDTO",
    "CreateLangfuseCredentialDTOProvider",
    "CreateLmntCredentialDTO",
    "CreateLmntCredentialDTOProvider",
    "CreateMakeCredentialDTO",
    "CreateMakeCredentialDTOProvider",
    "CreateMakeToolDTO",
    "CreateMakeToolDTOType",
    "CreateMistralCredentialDTO",
    "CreateMistralCredentialDTOProvider",
    "CreateNeuphonicCredentialDTO",
    "CreateNeuphonicCredentialDTOProvider",
    "CreateOpenAICredentialDTO",
    "CreateOpenAICredentialDTOProvider",
    "CreateOpenRouterCredentialDTO",
    "CreateOpenRouterCredentialDTOProvider",
    "CreateOrgDTO",
    "CreateOrgDTOChannel",
    "CreateOutboundCallDTO",
    "CreateOutputToolDTO",
    "CreateOutputToolDTOType",
    "CreatePerplexityAICredentialDTO",
    "CreatePerplexityAICredentialDTOProvider",
    "CreatePlayHTCredentialDTO",
    "CreatePlayHTCredentialDTOProvider",
    "CreateQueryToolDTO",
    "CreateQueryToolDTOType",
    "CreateRimeAICredentialDTO",
    "CreateRimeAICredentialDTOProvider",
    "CreateRunpodCredentialDTO",
    "CreateRunpodCredentialDTOProvider",
    "CreateS3CredentialDTO",
    "CreateS3CredentialDTOProvider",
    "CreateSmallestAICredentialDTO",
    "CreateSmallestAICredentialDTOProvider",
    "CreateSpeechmaticsCredentialDTO",
    "CreateSpeechmaticsCredentialDTOProvider",
    "CreateSquadDTO",
    "CreateSupabaseCredentialDTO",
    "CreateSupabaseCredentialDTOProvider",
    "CreateTavusCredentialDTO",
    "CreateTavusCredentialDTOProvider",
    "CreateTelnyxPhoneNumberDTO",
    "CreateTelnyxPhoneNumberDTOProvider",
    "CreateTestSuiteDto",
    "CreateTestSuiteRunDto",
    "CreateTestSuiteTestVoiceDto",
    "CreateTestSuiteTestVoiceDtoType",
    "CreateTextEditorToolDTO",
    "CreateTextEditorToolDTOName",
    "CreateTextEditorToolDTOSubType",
    "CreateTextEditorToolDTOType",
    "CreateTogetherAICredentialDTO",
    "CreateTogetherAICredentialDTOProvider",
    "CreateTokenDTO",
    "CreateTokenDTOTag",
    "CreateToolTemplateDTO",
    "CreateToolTemplateDTOProvider",
    "CreateToolTemplateDTOType",
    "CreateToolTemplateDTOVisibility",
    "CreateTransferCallToolDTO",
    "CreateTransferCallToolDTOType",
    "CreateTrieveCredentialDTO",
    "CreateTrieveCredentialDTOProvider",
    "CreateTrieveKnowledgeBaseDTO",
    "CreateTrieveKnowledgeBaseDTOProvider",
    "CreateTwilioCredentialDTO",
    "CreateTwilioCredentialDTOProvider",
    "CreateTwilioPhoneNumberDTO",
    "CreateTwilioPhoneNumberDTOProvider",
    "CreateVapiPhoneNumberDTO",
    "CreateVapiPhoneNumberDTOProvider",
    "CreateVoicemailToolDTO",
    "CreateVoicemailToolDTOType",
    "CreateVonageCredentialDTO",
    "CreateVonageCredentialDTOProvider",
    "CreateVonagePhoneNumberDTO",
    "CreateVonagePhoneNumberDTOProvider",
    "CreateWebCallDTO",
    "CreateWebhookCredentialDTO",
    "CreateWebhookCredentialDTOProvider",
    "CreateWorkflowDTO",
    "CreateXAiCredentialDTO",
    "CreateXAiCredentialDTOProvider",
    "CustomerCustomEndpointingRule",
    "CustomerCustomEndpointingRuleType",
    "CustomKnowledgeBase",
    "CustomKnowledgeBaseProvider",
    "CustomLLMCredential",
    "CustomLLMCredentialProvider",
    "CustomLLMModel",
    "CustomLLMModelMetadataSendMode",
    "CustomLLMModelProvider",
    "CustomMessage",
    "CustomMessageType",
    "CustomTranscriber",
    "CustomTranscriberProvider",
    "CustomVoice",
    "CustomVoiceProvider",
    "DeepgramCredential",
    "DeepgramCredentialProvider",
    "DeepgramTranscriber",
    "DeepgramTranscriberLanguage",
    "DeepgramTranscriberModelType0",
    "DeepgramTranscriberProvider",
    "DeepgramVoice",
    "DeepgramVoicePresetVoiceOptions",
    "DeepgramVoiceProvider",
    "DeepInfraCredential",
    "DeepInfraCredentialProvider",
    "DeepInfraModel",
    "DeepInfraModelProvider",
    "DeepSeekCredential",
    "DeepSeekCredentialProvider",
    "DeepSeekModel",
    "DeepSeekModelModel",
    "DeepSeekModelProvider",
    "DtmfTool",
    "DtmfToolType",
    "Edge",
    "EdgeMetadata",
    "ElevenLabsCredential",
    "ElevenLabsCredentialProvider",
    "ElevenLabsTranscriber",
    "ElevenLabsTranscriberLanguage",
    "ElevenLabsTranscriberModel",
    "ElevenLabsTranscriberProvider",
    "ElevenLabsVoice",
    "ElevenLabsVoiceModel",
    "ElevenLabsVoicePresetVoiceOptions",
    "ElevenLabsVoiceProvider",
    "EndCallTool",
    "EndCallToolType",
    "Error",
    "ExactReplacement",
    "ExactReplacementType",
    "FailedEdgeCondition",
    "FailedEdgeConditionType",
    "FallbackAzureVoice",
    "FallbackAzureVoicePresetVoiceOptions",
    "FallbackAzureVoiceProvider",
    "FallbackCartesiaVoice",
    "FallbackCartesiaVoiceLanguage",
    "FallbackCartesiaVoiceModel",
    "FallbackCartesiaVoiceProvider",
    "FallbackCustomVoice",
    "FallbackCustomVoiceProvider",
    "FallbackDeepgramVoice",
    "FallbackDeepgramVoicePresetVoiceOptions",
    "FallbackDeepgramVoiceProvider",
    "FallbackElevenLabsVoice",
    "FallbackElevenLabsVoiceModel",
    "FallbackElevenLabsVoicePresetVoiceOptions",
    "FallbackElevenLabsVoiceProvider",
    "FallbackHumeVoice",
    "FallbackHumeVoiceModel",
    "FallbackHumeVoiceProvider",
    "FallbackLMNTVoice",
    "FallbackLMNTVoicePresetVoiceOptions",
    "FallbackLMNTVoiceProvider",
    "FallbackNeetsVoice",
    "FallbackNeetsVoicePresetVoiceOptions",
    "FallbackNeetsVoiceProvider",
    "FallbackNeuphonicVoice",
    "FallbackNeuphonicVoiceLanguage",
    "FallbackNeuphonicVoiceModel",
    "FallbackNeuphonicVoiceProvider",
    "FallbackOpenAIVoice",
    "FallbackOpenAIVoiceProvider",
    "FallbackOpenAIVoiceVoiceId",
    "FallbackPlan",
    "FallbackPlayHTVoice",
    "FallbackPlayHTVoiceEmotion",
    "FallbackPlayHTVoiceLanguage",
    "FallbackPlayHTVoiceModel",
    "FallbackPlayHTVoicePresetVoiceOptions",
    "FallbackPlayHTVoiceProvider",
    "FallbackRimeAIVoice",
    "FallbackRimeAIVoiceModel",
    "FallbackRimeAIVoicePresetVoiceOptions",
    "FallbackRimeAIVoiceProvider",
    "FallbackSmallestAIVoice",
    "FallbackSmallestAIVoiceModel",
    "FallbackSmallestAIVoicePresetVoiceOptions",
    "FallbackSmallestAIVoiceProvider",
    "FallbackTavusVoice",
    "FallbackTavusVoicePresetVoiceOptions",
    "FallbackTavusVoiceProvider",
    "FallbackVapiVoice",
    "FallbackVapiVoiceProvider",
    "FallbackVapiVoiceVoiceId",
    "File",
    "FileMetadata",
    "FileObject",
    "FileStatus",
    "FormatPlan",
    "FormatPlanFormattersEnabled",
    "FunctionTool",
    "FunctionToolProviderDetails",
    "FunctionToolProviderDetailsType",
    "FunctionToolType",
    "FunctionToolWithToolCall",
    "FunctionToolWithToolCallType",
    "Gather",
    "GatherMetadata",
    "GatherType",
    "GcpCredential",
    "GcpCredentialProvider",
    "GcpKey",
    "GeminiMultimodalLivePrebuiltVoiceConfig",
    "GeminiMultimodalLivePrebuiltVoiceConfigVoiceName",
    "GeminiMultimodalLiveSpeechConfig",
    "GeminiMultimodalLiveVoiceConfig",
    "GhlTool",
    "GhlToolMetadata",
    "GhlToolProviderDetails",
    "GhlToolProviderDetailsType",
    "GhlToolType",
    "GhlToolWithToolCall",
    "GhlToolWithToolCallType",
    "GladiaCredential",
    "GladiaCredentialProvider",
    "GladiaTranscriber",
    "GladiaTranscriberLanguage",
    "GladiaTranscriberLanguageBehaviourType0",
    "GladiaTranscriberModelType0",
    "GladiaTranscriberProvider",
    "GoHighLevelCredential",
    "GoHighLevelCredentialProvider",
    "GoogleCredential",
    "GoogleCredentialProvider",
    "GoogleModel",
    "GoogleModelModel",
    "GoogleModelProvider",
    "GoogleRealtimeConfig",
    "GoogleVoicemailDetectionPlan",
    "GoogleVoicemailDetectionPlanProvider",
    "GroqCredential",
    "GroqCredentialProvider",
    "GroqModel",
    "GroqModelModel",
    "GroqModelProvider",
    "Hangup",
    "HangupMetadata",
    "HangupType",
    "Hook",
    "HookOn",
    "HumeCredential",
    "HumeCredentialProvider",
    "HumeVoice",
    "HumeVoiceModel",
    "HumeVoiceProvider",
    "ImportTwilioPhoneNumberDTO",
    "ImportVonagePhoneNumberDTO",
    "InflectionAICredential",
    "InflectionAICredentialProvider",
    "InflectionAIModel",
    "InflectionAIModelModel",
    "InflectionAIModelProvider",
    "InviteUserDTO",
    "InviteUserDTORole",
    "InvoicePlan",
    "JsonSchema",
    "JsonSchemaItems",
    "JsonSchemaProperties",
    "JsonSchemaType",
    "KeypadInputPlan",
    "KeypadInputPlanDelimiters",
    "KnowledgeBase",
    "KnowledgeBaseModel",
    "KnowledgeBaseProvider",
    "KnowledgeBaseResponseDocument",
    "LangfuseCredential",
    "LangfuseCredentialProvider",
    "LangfuseObservabilityPlan",
    "LangfuseObservabilityPlanProvider",
    "LmntCredential",
    "LmntCredentialProvider",
    "LMNTVoice",
    "LMNTVoicePresetVoiceOptions",
    "LMNTVoiceProvider",
    "Log",
    "LoggingControllerLogsDeleteQueryType",
    "LoggingControllerLogsQuerySortOrder",
    "LoggingControllerLogsQueryType",
    "LogicEdgeCondition",
    "LogicEdgeConditionType",
    "LogRequestBody",
    "LogRequestHeaders",
    "LogRequestHttpMethod",
    "LogResource",
    "LogResponseBody",
    "LogsPaginatedResponse",
    "LogType",
    "MakeCredential",
    "MakeCredentialProvider",
    "MakeTool",
    "MakeToolMetadata",
    "MakeToolProviderDetails",
    "MakeToolProviderDetailsType",
    "MakeToolType",
    "MakeToolWithToolCall",
    "MakeToolWithToolCallType",
    "MessagePlan",
    "Metrics",
    "MetricsBillDailyBreakdown",
    "MetricsCallCountDailyBreakdown",
    "MetricsCallMinutesAverageDailyBreakdown",
    "MetricsCallMinutesDailyBreakdown",
    "MistralCredential",
    "MistralCredentialProvider",
    "ModelCost",
    "ModelCostModel",
    "ModelCostType",
    "Monitor",
    "MonitorPlan",
    "NeetsVoice",
    "NeetsVoicePresetVoiceOptions",
    "NeetsVoiceProvider",
    "NeuphonicCredential",
    "NeuphonicCredentialProvider",
    "NeuphonicVoice",
    "NeuphonicVoiceLanguage",
    "NeuphonicVoiceModel",
    "NeuphonicVoiceProvider",
    "OAuth2AuthenticationPlan",
    "OAuth2AuthenticationPlanType",
    "Oauth2AuthenticationSession",
    "OpenAICredential",
    "OpenAICredentialProvider",
    "OpenAIFunction",
    "OpenAIFunctionParameters",
    "OpenAIFunctionParametersProperties",
    "OpenAIFunctionParametersType",
    "OpenAIMessage",
    "OpenAIMessageRole",
    "OpenAIModel",
    "OpenAIModelFallbackModels",
    "OpenAIModelModel",
    "OpenAIModelProvider",
    "OpenAIVoice",
    "OpenAIVoicemailDetectionPlan",
    "OpenAIVoicemailDetectionPlanProvider",
    "OpenAIVoiceProvider",
    "OpenAIVoiceVoiceId",
    "OpenRouterCredential",
    "OpenRouterCredentialProvider",
    "OpenRouterModel",
    "OpenRouterModelProvider",
    "Org",
    "OrgChannel",
    "OrgPlan",
    "OrgPlanIncludedProvidersItem",
    "OutputTool",
    "OutputToolType",
    "PaginationMeta",
    "PerplexityAICredential",
    "PerplexityAICredentialProvider",
    "PerplexityAIModel",
    "PerplexityAIModelProvider",
    "PhoneNumberPaginatedResponse",
    "PlayHTCredential",
    "PlayHTCredentialProvider",
    "PlayHTVoice",
    "PlayHTVoiceEmotion",
    "PlayHTVoiceLanguage",
    "PlayHTVoiceModel",
    "PlayHTVoicePresetVoiceOptions",
    "PlayHTVoiceProvider",
    "QueryTool",
    "QueryToolType",
    "RegexOption",
    "RegexOptionType",
    "RegexReplacement",
    "RegexReplacementType",
    "RimeAICredential",
    "RimeAICredentialProvider",
    "RimeAIVoice",
    "RimeAIVoiceModel",
    "RimeAIVoicePresetVoiceOptions",
    "RimeAIVoiceProvider",
    "RunpodCredential",
    "RunpodCredentialProvider",
    "S3Credential",
    "S3CredentialProvider",
    "Say",
    "SayHook",
    "SayHookMetadata",
    "SayHookType",
    "SayMetadata",
    "SayType",
    "SbcConfiguration",
    "Server",
    "ServerHeaders",
    "ServerMessage",
    "ServerMessageAssistantRequest",
    "ServerMessageAssistantRequestType",
    "ServerMessageConversationUpdate",
    "ServerMessageConversationUpdateType",
    "ServerMessageEndOfCallReport",
    "ServerMessageEndOfCallReportEndedReason",
    "ServerMessageEndOfCallReportType",
    "ServerMessageHang",
    "ServerMessageHangType",
    "ServerMessageKnowledgeBaseRequest",
    "ServerMessageKnowledgeBaseRequestType",
    "ServerMessageLanguageChangeDetected",
    "ServerMessageLanguageChangeDetectedType",
    "ServerMessageModelOutput",
    "ServerMessageModelOutputOutput",
    "ServerMessageModelOutputType",
    "ServerMessagePhoneCallControl",
    "ServerMessagePhoneCallControlRequest",
    "ServerMessagePhoneCallControlType",
    "ServerMessageResponse",
    "ServerMessageResponseAssistantRequest",
    "ServerMessageResponseKnowledgeBaseRequest",
    "ServerMessageResponseToolCalls",
    "ServerMessageResponseTransferDestinationRequest",
    "ServerMessageResponseVoiceRequest",
    "ServerMessageSpeechUpdate",
    "ServerMessageSpeechUpdateRole",
    "ServerMessageSpeechUpdateStatus",
    "ServerMessageSpeechUpdateType",
    "ServerMessageStatusUpdate",
    "ServerMessageStatusUpdateEndedReason",
    "ServerMessageStatusUpdateInboundPhoneCallDebuggingArtifacts",
    "ServerMessageStatusUpdateStatus",
    "ServerMessageStatusUpdateType",
    "ServerMessageToolCalls",
    "ServerMessageToolCallsType",
    "ServerMessageTranscript",
    "ServerMessageTranscriptRole",
    "ServerMessageTranscriptTranscriptType",
    "ServerMessageTranscriptType",
    "ServerMessageTransferDestinationRequest",
    "ServerMessageTransferDestinationRequestType",
    "ServerMessageTransferUpdate",
    "ServerMessageTransferUpdateFromStepRecord",
    "ServerMessageTransferUpdateToStepRecord",
    "ServerMessageTransferUpdateType",
    "ServerMessageUserInterrupted",
    "ServerMessageUserInterruptedType",
    "ServerMessageVoiceInput",
    "ServerMessageVoiceInputType",
    "ServerMessageVoiceRequest",
    "ServerMessageVoiceRequestType",
    "SipAuthentication",
    "SipTrunkGateway",
    "SipTrunkGatewayOutboundProtocol",
    "SipTrunkOutboundAuthenticationPlan",
    "SipTrunkOutboundSipRegisterPlan",
    "SmallestAICredential",
    "SmallestAICredentialProvider",
    "SmallestAIVoice",
    "SmallestAIVoiceModel",
    "SmallestAIVoicePresetVoiceOptions",
    "SmallestAIVoiceProvider",
    "SpeechmaticsCredential",
    "SpeechmaticsCredentialProvider",
    "SpeechmaticsTranscriber",
    "SpeechmaticsTranscriberLanguage",
    "SpeechmaticsTranscriberModel",
    "SpeechmaticsTranscriberProvider",
    "Squad",
    "SquadMemberDTO",
    "StartSpeakingPlan",
    "StartSpeakingPlanSmartEndpointingEnabledType1",
    "StopSpeakingPlan",
    "StructuredDataPlan",
    "StructuredDataPlanMessagesItem",
    "Subscription",
    "SubscriptionStatus",
    "SubscriptionType",
    "SuccessEvaluationPlan",
    "SuccessEvaluationPlanMessagesItem",
    "SuccessEvaluationPlanRubric",
    "SummaryPlan",
    "SummaryPlanMessagesItem",
    "SupabaseBucketPlan",
    "SupabaseBucketPlanRegion",
    "SupabaseCredential",
    "SupabaseCredentialProvider",
    "SyncVoiceLibraryDTO",
    "SyncVoiceLibraryDTOProviders",
    "SystemMessage",
    "TalkscriberTranscriber",
    "TalkscriberTranscriberLanguage",
    "TalkscriberTranscriberModel",
    "TalkscriberTranscriberProvider",
    "TavusConversationProperties",
    "TavusCredential",
    "TavusCredentialProvider",
    "TavusVoice",
    "TavusVoicePresetVoiceOptions",
    "TavusVoiceProvider",
    "TelnyxPhoneNumber",
    "TelnyxPhoneNumberProvider",
    "TelnyxPhoneNumberStatus",
    "Template",
    "TemplateProvider",
    "TemplateType",
    "TemplateVisibility",
    "TestSuite",
    "TestSuiteControllerFindAllPaginatedSortOrder",
    "TestSuiteRun",
    "TestSuiteRunControllerFindAllPaginatedSortOrder",
    "TestSuiteRunScorerAI",
    "TestSuiteRunScorerAIResult",
    "TestSuiteRunScorerAIType",
    "TestSuiteRunsPaginatedResponse",
    "TestSuiteRunStatus",
    "TestSuiteRunTestAttempt",
    "TestSuiteRunTestAttemptCall",
    "TestSuiteRunTestResult",
    "TestSuitesPaginatedResponse",
    "TestSuiteTestControllerFindAllPaginatedSortOrder",
    "TestSuiteTestScorerAI",
    "TestSuiteTestScorerAIType",
    "TestSuiteTestsPaginatedResponse",
    "TestSuiteTestVoice",
    "TestSuiteTestVoiceType",
    "TextContent",
    "TextContentLanguage",
    "TextContentType",
    "TextEditorTool",
    "TextEditorToolName",
    "TextEditorToolSubType",
    "TextEditorToolType",
    "TextEditorToolWithToolCall",
    "TextEditorToolWithToolCallName",
    "TextEditorToolWithToolCallSubType",
    "TextEditorToolWithToolCallType",
    "TimeRange",
    "TimeRangeStep",
    "TogetherAICredential",
    "TogetherAICredentialProvider",
    "TogetherAIModel",
    "TogetherAIModelProvider",
    "Token",
    "TokenRestrictions",
    "TokenTag",
    "ToolCall",
    "ToolCallFunction",
    "ToolCallFunctionArguments",
    "ToolCallMessage",
    "ToolCallMessageToolCallsItem",
    "ToolCallResult",
    "ToolCallResultMessage",
    "ToolCallType",
    "ToolMessageComplete",
    "ToolMessageCompleteRole",
    "ToolMessageCompleteType",
    "ToolMessageDelayed",
    "ToolMessageDelayedType",
    "ToolMessageFailed",
    "ToolMessageFailedType",
    "ToolMessageStart",
    "ToolMessageStartType",
    "ToolTemplateMetadata",
    "ToolTemplateSetup",
    "TranscriberCost",
    "TranscriberCostTranscriber",
    "TranscriberCostType",
    "TranscriptionEndpointingPlan",
    "TranscriptPlan",
    "Transfer",
    "TransferAssistantHookAction",
    "TransferAssistantHookActionType",
    "TransferCallTool",
    "TransferCallToolType",
    "TransferDestination",
    "TransferDestinationAssistant",
    "TransferDestinationAssistantTransferMode",
    "TransferDestinationAssistantType",
    "TransferDestinationNumber",
    "TransferDestinationNumberType",
    "TransferDestinationSip",
    "TransferDestinationSipSipHeaders",
    "TransferDestinationSipType",
    "TransferDestinationStep",
    "TransferDestinationStepType",
    "TransferMetadata",
    "TransferPlan",
    "TransferPlanMode",
    "TransferPlanSipVerb",
    "TransferType",
    "Transport",
    "TransportConfigurationTwilio",
    "TransportConfigurationTwilioProvider",
    "TransportConfigurationTwilioRecordingChannels",
    "TransportCost",
    "TransportCostProvider",
    "TransportCostType",
    "TransportProvider",
    "TrieveCredential",
    "TrieveCredentialProvider",
    "TrieveKnowledgeBase",
    "TrieveKnowledgeBaseChunkPlan",
    "TrieveKnowledgeBaseCreate",
    "TrieveKnowledgeBaseCreateType",
    "TrieveKnowledgeBaseImport",
    "TrieveKnowledgeBaseImportType",
    "TrieveKnowledgeBaseProvider",
    "TrieveKnowledgeBaseSearchPlan",
    "TrieveKnowledgeBaseSearchPlanSearchType",
    "TwilioCredential",
    "TwilioCredentialProvider",
    "TwilioPhoneNumber",
    "TwilioPhoneNumberProvider",
    "TwilioPhoneNumberStatus",
    "TwilioVoicemailDetectionPlan",
    "TwilioVoicemailDetectionPlanProvider",
    "TwilioVoicemailDetectionPlanVoicemailDetectionTypes",
    "UpdateAnthropicCredentialDTO",
    "UpdateAnyscaleCredentialDTO",
    "UpdateAssemblyAICredentialDTO",
    "UpdateAssistantDTO",
    "UpdateAssistantDTOBackgroundSound",
    "UpdateAssistantDTOClientMessages",
    "UpdateAssistantDTOFirstMessageMode",
    "UpdateAssistantDTOMetadata",
    "UpdateAssistantDTOServerMessages",
    "UpdateAzureCredentialDTO",
    "UpdateAzureCredentialDTORegion",
    "UpdateAzureCredentialDTOService",
    "UpdateAzureOpenAICredentialDTO",
    "UpdateAzureOpenAICredentialDTOModels",
    "UpdateAzureOpenAICredentialDTORegion",
    "UpdateBashToolDTO",
    "UpdateBashToolDTOName",
    "UpdateBashToolDTOSubType",
    "UpdateByoPhoneNumberDTO",
    "UpdateByoSipTrunkCredentialDTO",
    "UpdateCallDTO",
    "UpdateCartesiaCredentialDTO",
    "UpdateCerebrasCredentialDTO",
    "UpdateCloudflareCredentialDTO",
    "UpdateComputerToolDTO",
    "UpdateComputerToolDTOName",
    "UpdateComputerToolDTOSubType",
    "UpdateCustomKnowledgeBaseDTO",
    "UpdateCustomLLMCredentialDTO",
    "UpdateDeepgramCredentialDTO",
    "UpdateDeepInfraCredentialDTO",
    "UpdateDeepSeekCredentialDTO",
    "UpdateDtmfToolDTO",
    "UpdateElevenLabsCredentialDTO",
    "UpdateEndCallToolDTO",
    "UpdateFileDTO",
    "UpdateFunctionToolDTO",
    "UpdateGcpCredentialDTO",
    "UpdateGhlToolDTO",
    "UpdateGladiaCredentialDTO",
    "UpdateGoHighLevelCredentialDTO",
    "UpdateGoogleCredentialDTO",
    "UpdateGroqCredentialDTO",
    "UpdateHumeCredentialDTO",
    "UpdateInflectionAICredentialDTO",
    "UpdateLangfuseCredentialDTO",
    "UpdateLmntCredentialDTO",
    "UpdateMakeCredentialDTO",
    "UpdateMakeToolDTO",
    "UpdateMistralCredentialDTO",
    "UpdateNeuphonicCredentialDTO",
    "UpdateOpenAICredentialDTO",
    "UpdateOpenRouterCredentialDTO",
    "UpdateOrgDTO",
    "UpdateOrgDTOChannel",
    "UpdateOutputToolDTO",
    "UpdatePerplexityAICredentialDTO",
    "UpdatePlayHTCredentialDTO",
    "UpdateQueryToolDTO",
    "UpdateRimeAICredentialDTO",
    "UpdateRunpodCredentialDTO",
    "UpdateS3CredentialDTO",
    "UpdateSmallestAICredentialDTO",
    "UpdateSpeechmaticsCredentialDTO",
    "UpdateSquadDTO",
    "UpdateSupabaseCredentialDTO",
    "UpdateTavusCredentialDTO",
    "UpdateTelnyxPhoneNumberDTO",
    "UpdateTestSuiteDto",
    "UpdateTestSuiteRunDto",
    "UpdateTestSuiteTestVoiceDto",
    "UpdateTextEditorToolDTO",
    "UpdateTextEditorToolDTOName",
    "UpdateTextEditorToolDTOSubType",
    "UpdateTogetherAICredentialDTO",
    "UpdateTokenDTO",
    "UpdateTokenDTOTag",
    "UpdateToolTemplateDTO",
    "UpdateToolTemplateDTOProvider",
    "UpdateToolTemplateDTOType",
    "UpdateToolTemplateDTOVisibility",
    "UpdateTransferCallToolDTO",
    "UpdateTrieveCredentialDTO",
    "UpdateTrieveKnowledgeBaseDTO",
    "UpdateTwilioCredentialDTO",
    "UpdateTwilioPhoneNumberDTO",
    "UpdateUserRoleDTO",
    "UpdateUserRoleDTORole",
    "UpdateVapiPhoneNumberDTO",
    "UpdateVonageCredentialDTO",
    "UpdateVonagePhoneNumberDTO",
    "UpdateWebhookCredentialDTO",
    "UpdateWorkflowDTO",
    "UpdateXAiCredentialDTO",
    "User",
    "UserMessage",
    "VapiCost",
    "VapiCostSubType",
    "VapiCostType",
    "VapiModel",
    "VapiModelProvider",
    "VapiPhoneNumber",
    "VapiPhoneNumberProvider",
    "VapiPhoneNumberStatus",
    "VapiVoice",
    "VapiVoiceProvider",
    "VapiVoiceVoiceId",
    "VoiceCost",
    "VoiceCostType",
    "VoiceCostVoice",
    "VoiceLibrary",
    "VoiceLibraryGender",
    "VoiceLibraryProvider",
    "VoiceLibraryVoiceResponse",
    "VoiceLibraryVoiceResponseAge",
    "VoicemailDetectionCost",
    "VoicemailDetectionCostModel",
    "VoicemailDetectionCostProvider",
    "VoicemailDetectionCostType",
    "VonageCredential",
    "VonageCredentialProvider",
    "VonagePhoneNumber",
    "VonagePhoneNumberProvider",
    "VonagePhoneNumberStatus",
    "WebhookCredential",
    "WebhookCredentialProvider",
    "Workflow",
    "XAiCredential",
    "XAiCredentialProvider",
    "XaiModel",
    "XaiModelModel",
    "XaiModelProvider",
)
